import {PublicError,mutationOrigin} from '../../../../lib/app-errors';
import {database} from '../../../../db';
import {owner,readJSON,routeError} from '../../../../lib/history';
import {ownedProject,projectInput} from '../../../../lib/projects';
type Context={params:Promise<{id:string}>};
export async function GET(request:Request,{params}:Context){try{const {id}=await params;return Response.json({project:await ownedProject(id,owner(request))});}catch(e){return routeError(e);}}
export async function PATCH(request:Request,{params}:Context){try{const {id}=await params,user=owner(request),p=await ownedProject(id,user,'manage'),input=await readJSON(request),v=projectInput({...p,...input});const status=input.status===undefined?p.status:String(input.status);if(status!==p.status&&p.role!=='owner')throw new PublicError('Only the owner can archive or restore a project.',403);if(!['active','archived'].includes(status))throw new PublicError('Invalid project status.');const db=database();if(await db.prepare('SELECT id FROM projects WHERE owner=? AND site=? AND id<>?').bind(p.owner,v.site,id).first())throw new PublicError('A project for this website already exists.');if(v.site!==p.site&&await db.prepare('SELECT id FROM audit_runs WHERE project=? LIMIT 1').bind(id).first())throw new PublicError('A website with saved audits cannot be changed. Create a new project for the new website.');await db.prepare('UPDATE projects SET name=?,site=?,description=?,status=?,updated=? WHERE id=? AND owner=?').bind(v.name,v.site,v.description,status,new Date().toISOString(),id,p.owner).run();return Response.json({project:await ownedProject(id,user)});}catch(e){return routeError(e);}}
// Delete means archive. Retain audit history; the UI states this retention rule explicitly.
export async function DELETE(request:Request,{params}:Context){try{mutationOrigin(request);const {id}=await params,user=owner(request);await ownedProject(id,user,'owner');await database().prepare('UPDATE projects SET status=\'archived\',updated=? WHERE id=? AND owner=?').bind(new Date().toISOString(),id,user).run();return Response.json({archived:true,historyRetained:true});}catch(e){return routeError(e);}}
