'use client';
import {useState} from 'react';
import type {Report} from '../lib/audit';
type Revision={id:string;audited:string;status:string;error:string|null;scores:Report['scores']|null;changes:{resolved:string[];introduced:string[];scoreChanges:Record<string,number|null>|null;scopeChanged?:boolean}|null};
export function AuditHistory({run,url,onOpen}:{run:string;url:string;onOpen:(report:Report)=>void}){
 const [revisions,setRevisions]=useState<Revision[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const request=async(query:string)=>{const response=await fetch(`/api/runs/${encodeURIComponent(run)}/page?${query}`);const data=await response.json() as {error?:string;revisions:Revision[];revision:{report:Report|null;error:string|null}};if(!response.ok)throw Error(data.error||'Unable to load history.');return data;};
 async function load(){if(revisions){setRevisions(null);return;}setBusy(true);setError('');try{setRevisions((await request('url='+encodeURIComponent(url))).revisions);}catch(e){setError(e instanceof Error?e.message:'Unable to load history.');}finally{setBusy(false);}}
 async function open(id:string){setBusy(true);setError('');try{const r=(await request('revision='+encodeURIComponent(id))).revision;if(r.report)onOpen(r.report);else setError(r.error||'This attempt has no report.');}catch(e){setError(e instanceof Error?e.message:'Unable to open revision.');}finally{setBusy(false);}}
 return <div className="audit-history"><button className="text-button" disabled={busy} onClick={()=>void load()}>{busy?'Loading…':revisions?'Hide history':'Audit history'}</button>{error&&<p role="alert">{error}</p>}{revisions&&<div>{!revisions.length&&<p>No revisions recorded yet. Existing results are preserved on the next re-audit.</p>}{revisions.map(r=><div className="history-revision" key={r.id}><strong>{new Date(r.audited).toLocaleString()}</strong><p>{r.scores?Object.entries(r.scores).map(([c,v])=>`${c}: ${v??'unmeasured'}`).join(' · '):r.status}</p>{r.changes?.scopeChanged&&<p>Extraction version or target phrase changed; fix counts are not compared.</p>}<small>{r.changes?.resolved.length||0} groups now passing · {r.changes?.introduced.length||0} newly flagged</small>{r.error&&<p>{r.error}</p>}<button className="text-button" disabled={busy||!r.scores} onClick={()=>void open(r.id)}>Open saved revision</button></div>)}</div>}</div>;
}
