'use client';
import {useEffect,useState} from 'react';
import type {WebsiteIntelligence,Opportunity} from '../lib/content-intelligence';
import {projectRequest} from './page';
type View='Content Intelligence'|'Topics'|'Content Gaps'|'Opportunities';
const GAP_TYPES=['All','Topic','Question','Content','Internal Linking','Answer Readiness','Support'];

export function ContentIntelligence({project,run,view,canEdit}:{project:string;run:string|null;view:View;canEdit:boolean}){
 const[data,setData]=useState<WebsiteIntelligence|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[filter,setFilter]=useState('All'),[saving,setSaving]=useState('');
 async function load(){if(!run)return;setLoading(true);try{setData(await projectRequest<WebsiteIntelligence>(`/api/projects/${encodeURIComponent(project)}/intelligence?run=${encodeURIComponent(run)}`));setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load content intelligence.');}finally{setLoading(false);}}
 useEffect(()=>{setData(null);setFilter('All');void load();},[project,run]);
 async function update(item:Opportunity,status:string){if(!run)return;setSaving(item.id);try{await projectRequest(`/api/projects/${encodeURIComponent(project)}/intelligence`,{method:'PATCH',body:JSON.stringify({run,opportunity:item.id,status})});setData(current=>current?{...current,statuses:{...current.statuses,[item.id]:status}}:current);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to update the opportunity.');}finally{setSaving('');}}
 if(!run)return <section className="panel"><h2>{view}</h2><p>Run a website audit to analyze its saved page content.</p></section>;
 if(!data)return <section className="panel"><h2>{view}</h2>{loading?<p role="status">Loading saved page intelligence…</p>:<><p role="alert">{error||'Analysis is unavailable.'}</p><button className="secondary" onClick={()=>void load()}>Try again</button></>}</section>;
 const coverage=data.coverage;
 const intro=<section className="panel"><h2>{view}</h2><p>{coverage.analyzed} pages analyzed from {coverage.audited} completed reports; {coverage.selected} selected, {coverage.discovered} discovered.</p><p>{coverage.note}</p>{coverage.analyzed===0&&<p role="status">This audit predates content intelligence. Re-audit a page to create a versioned analysis from its current source.</p>}{error&&<p role="alert" className="error">{error}</p>}</section>;
 if(view==='Content Intelligence')return <>{intro}{data.pages.map(p=><details className="panel detail-accordion" key={p.pageId}><summary><div><strong>{p.topic.primary||p.url}</strong><p>{p.url} · {p.contentStrength.label} · Likely intent: {p.intent.likely} ({p.intent.confidence} confidence)</p></div><span aria-hidden="true">▾</span></summary><div className="detail-accordion-content intelligence-detail"><p>{p.topic.basis} Topic confidence: {p.topic.confidence}. Page type: {p.pageType}.</p><h3>Content strength signals</h3><ul>{p.contentStrength.signals.map(s=><li key={s.label}><strong>{s.label} · {s.state}</strong><span>{s.evidence}</span>{s.selector&&<code>{s.selector}</code>}</li>)}</ul><h3>Observed answer structure</h3><p>{p.answerReadiness.label}. {p.answerReadiness.signals.join(' ')||'No clear answer structure detected.'}</p><h3>Questions in source</h3>{p.questions.length?p.questions.map(q=><div className="project-observation" key={q.selector+q.text}><strong>{q.text} · {q.state}</strong><p>{q.answer||'No adjacent answer text detected.'}</p><code>{q.selector||'Paragraph context'}</code></div>):<p>No explicit questions detected in the extracted source.</p>}<h3>Observed support signals</h3>{p.trustSignals.length?<ul>{p.trustSignals.map((s,i)=><li key={i}>{s.text}</li>)}</ul>:<p>No supporting external content links or author/date metadata observed. This does not assess credibility.</p>}<h3>Internal links in content</h3><p>{p.internalLinking.contextual.length} outgoing · {p.internalLinking.incoming?.length??'Not measured'} incoming from audited pages.</p><p>{p.limitations.join(' ')}</p></div></details>)}{data.relationships.length>0&&<section className="panel"><h2>Page relationships</h2>{data.relationships.map((r,i)=><div className="project-observation" key={i}><strong>{r.kind} · {r.confidence} confidence</strong><p>{r.urls.join(' ↔ ')}</p><p>{r.evidence} {r.note}</p></div>)}</section>}</>;
 if(view==='Topics')return <>{intro}<section className="panel"><h2>Topics observed on audited pages</h2><p>Topics come from each page’s content H1 or title. They are editorial inferences, not search-engine classifications.</p>{data.topics.map((t,i)=><details className="project-issue-page" key={i}><summary><div><strong>{t.topic}</strong><p>{t.url} · {t.confidence} confidence</p></div><span aria-hidden="true">▾</span></summary><div className="detail-accordion-content"><strong>Related headings</strong><ul>{t.related.map((s,j)=><li key={j}>{s.text} <code>{s.selector}</code></li>)}</ul>{!t.related.length&&<p>No supporting headings observed.</p>}</div></details>)}{!data.topics.length&&<p>No topics extracted yet.</p>}</section><section className="panel"><h2>Potential topic clusters</h2><p>Grouped only when multiple analyzed pages share the same normalized heading or title topic.</p>{data.clusters.map((c,i)=><div className="project-observation" key={i}><strong>{c.topic} · {c.confidence} confidence</strong><p>{c.pages.join(' · ')}</p><p>{c.evidence} {c.note}</p></div>)}{!data.clusters.length&&<p>No repeated primary topic was observed in these analyzed pages.</p>}</section></>;
 const list=filter==='All'?data.opportunities:data.opportunities.filter(o=>o.type===filter);
 return <>{intro}<section className="panel"><h2>{view==='Content Gaps'?'Evidence-backed content gaps':'Content opportunities'}</h2><p>{view==='Content Gaps'?'These are possible improvements derived from observed page content. Confirm relevance before editing.':'Opportunities are separate from the 29 SEO/AEO/GEO issue checks. Each suggestion cites its source evidence.'}</p><label className="intelligence-filter">Type<select value={filter} onChange={e=>setFilter(e.target.value)}>{GAP_TYPES.map(t=><option key={t}>{t}</option>)}</select></label>{list.map(o=><details className="project-issue-page" key={o.id}><summary><div><strong>{o.title}</strong><p>{o.type} · {o.confidence} confidence · {o.priority} priority · {data.statuses[o.id]||'Open'}</p></div><span aria-hidden="true">▾</span></summary><div className="detail-accordion-content intelligence-detail"><p><strong>Page:</strong> {o.page}</p><p><strong>Why review it:</strong> {o.why}</p><p><strong>Evidence:</strong> {o.evidence}</p>{o.selector&&<p><strong>Selector:</strong> <code>{o.selector}</code></p>}<p><strong>Suggested action:</strong> {o.action}</p>{view==='Opportunities'&&canEdit&&<label>Status<select value={data.statuses[o.id]||'Open'} disabled={saving===o.id} onChange={e=>void update(o,e.target.value)}>{['Open','In Progress','Resolved','Dismissed'].map(s=><option key={s}>{s}</option>)}</select></label>}</div></details>)}{!list.length&&<p>No evidence-backed {view==='Content Gaps'?'gaps':'opportunities'} match this view.</p>}</section></>;
}
