'use client';
import {useMemo,useState} from 'react';
import type {PageAudit,Run} from '../lib/history';
import type {Report} from '../lib/audit';
import {comparePages} from '../lib/cross-page';
import {linkGraph} from '../lib/project-analysis';
import {currentPageAttempts} from '../lib/website-findings';

export function CrossPageAnalysis({run,pages,onOpen}:{run:Run|null;pages:PageAudit[];onOpen:(report:Report)=>void}){
 const [category,setCategory]=useState('All'),[search,setSearch]=useState(''),[sort,setSort]=useState('Type'),[limit,setLimit]=useState(25);
 const current=useMemo(()=>currentPageAttempts(pages),[pages]);
 const comparison=useMemo(()=>comparePages(current),[current]);
 const graph=useMemo(()=>run?linkGraph(run,current):null,[run,current]);
 const reports=new Map(current.filter(p=>p.report).map(p=>[p.url,p.report!]));
 const categoryOf=(kind:string)=>kind.includes('title')||kind.includes('description')?'Metadata':kind.includes('H1')?'Headings':'Content';
 const visible=comparison.groups.filter(g=>(category==='All'||categoryOf(g.kind)===category)&&(!search||[g.value,g.kind,...g.urls].join(' ').toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>sort==='Similarity'?((b.similarity||0)-(a.similarity||0)):sort==='Pages'?b.urls.length-a.urls.length:sort==='A–Z'?a.value.localeCompare(b.value):a.kind.localeCompare(b.kind)||a.value.localeCompare(b.value));
 const linkPages=(graph?.pages||[]).filter(p=>(p.incoming.length||p.outgoing.length)&&(!search||[p.url,...p.incoming,...p.outgoing].join(' ').toLowerCase().includes(search.toLowerCase())));
 const canonical=current.filter(p=>p.report?.canonicalResult&&(!search||[p.url,p.report.canonicalResult.declared].join(' ').toLowerCase().includes(search.toLowerCase())));
 return <section className="cross-page-analysis" aria-label="Cross-page analysis"><div className="cross-page-intro"><h2>Cross-page Analysis</h2><p>Compare captured metadata, H1s, main content and internal relationships within this selected audit. Similarity is a review signal, not proof of duplicate content.</p><small>Selected audit: {run?new Date(run.created).toLocaleString():'No saved audit selected'} · Analysis method v{comparison.analysisVersion}</small></div>
  <div className="cross-page-summary"><div><strong>{comparison.compared}</strong><span>Pages compared</span></div><div><strong>{comparison.groups.length}</strong><span>Comparison groups</span></div><div><strong>{comparison.groups.filter(g=>g.kind==='Duplicate title').length}</strong><span>Duplicate titles</span></div><div><strong>{comparison.groups.filter(g=>g.kind==='Duplicate meta description').length}</strong><span>Duplicate descriptions</span></div><div><strong>{comparison.groups.filter(g=>g.kind==='Duplicate H1').length}</strong><span>Duplicate H1s</span></div><div><strong>{comparison.groups.filter(g=>g.kind==='Similar content').length}</strong><span>Similar content</span></div></div>
  <div className="cross-page-controls"><div role="group" aria-label="Comparison category">{['All','Metadata','Headings','Content','Links','Canonical'].map(item=><button type="button" aria-pressed={category===item} onClick={()=>{setCategory(item);setLimit(25);}} key={item}>{item}</button>)}</div><label>Search comparisons<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title, page or URL"/></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}>{['Type','Similarity','Pages','A–Z'].map(v=><option key={v}>{v}</option>)}</select></label></div>
  {category!=='Links'&&category!=='Canonical'&&<div className="cross-page-results"><p>{visible.length} measured groups match this view. Similarity compared {comparison.similarityCompared} pages with enough retained content; {comparison.insufficientContent} were ineligible for that comparison.</p>{visible.slice(0,limit).map((g,i)=><details className="cross-page-result" key={g.kind+g.value+i}><summary><div><strong>{g.kind}</strong><span>{g.value}</span><small>{g.urls.length} pages{g.similarity!==undefined?` · ${g.similarity}% measured overlap`:''} · {g.confidence}</small></div><span aria-hidden="true">⌄</span></summary><div className="cross-page-detail"><p><strong>Why matched:</strong> {g.why}</p><p><strong>Method:</strong> {g.method}</p>{g.wordsCompared&&<p><strong>Words compared:</strong> {g.wordsCompared[0]} and {g.wordsCompared[1]} · {g.sharedShingles} matching five-word sequences</p>}{g.evidence.length>0&&<div><strong>Captured evidence</strong><ul>{g.evidence.map((value,j)=><li key={j}>{value}</li>)}</ul></div>}<strong>Pages in this group</strong><ul>{g.urls.map(url=><li key={url}><span>{url}</span>{reports.get(url)&&<button className="text-button" onClick={()=>onOpen(reports.get(url)!)}>Open saved report</button>}<a href={url} target="_blank" rel="noreferrer">Open page ↗</a></li>)}</ul><small>Audit {g.auditId||run?.id||'not recorded'} · method {g.analysisVersion} · captured {g.measuredAt?new Date(g.measuredAt).toLocaleString():'date unavailable'}</small></div></details>)}{visible.length>limit&&<button className="secondary" onClick={()=>setLimit(n=>n+25)}>Show 25 more groups</button>}{!visible.length&&<p>No measured comparison groups match. This does not establish that pages have no overlapping topics.</p>}</div>}
  {category==='Links'&&<div className="cross-page-results"><h3>Internal link relationships</h3><p>{graph?.coverage||'No crawl data yet.'} No incoming link detected within the audited crawl does not prove a page is orphaned.</p>{linkPages.slice(0,limit).map(p=><details className="cross-page-result" key={p.url}><summary><div><strong>{p.url}</strong><small>{p.incoming.length} incoming · {p.outgoing.length} outgoing</small></div><span aria-hidden="true">⌄</span></summary><div className="cross-page-detail"><p>Method: Internal links extracted from the captured initial HTML of audited pages.</p><strong>Incoming from</strong><ul>{p.incoming.map(u=><li key={u}>{u}</li>)}</ul><strong>Outgoing to</strong><ul>{p.outgoing.map(u=><li key={u}>{u}</li>)}</ul></div></details>)}{linkPages.length>limit&&<button className="secondary" onClick={()=>setLimit(n=>n+25)}>Show 25 more pages</button>}{!linkPages.length&&<p>No internal link relationships were detected in the audited pages.</p>}</div>}
  {category==='Canonical'&&<div className="cross-page-results"><h3>Canonical destination observations</h3><p>HTTP observations of declared canonicals; pointing to another page is not automatically a defect.</p>{canonical.slice(0,limit).map(p=><div className="cross-page-result cross-page-canonical" key={p.url}><strong>{p.url}</strong><p>Declared: {p.report!.canonicalResult!.declared||'Not declared'}</p><p>{p.report!.canonicalResult!.relation} · {p.report!.canonicalResult!.observation?.status?`HTTP ${p.report!.canonicalResult!.observation?.status}`:'Not verified'} · {p.report!.canonicalResult!.note}</p></div>)}{canonical.length>limit&&<button className="secondary" onClick={()=>setLimit(n=>n+25)}>Show 25 more observations</button>}{!canonical.length&&<p>No canonical destination observations in the selected audit.</p>}</div>}
  <details className="website-technical-details"><summary>Comparison scope and method</summary><p>{comparison.method}</p><p>Comparison groups belong to this selected saved audit. They do not establish search engine decisions, ranking changes or keyword cannibalization.</p></details>
 </section>;
}
