'use client';
import {useState} from 'react';
import type {Report} from '../lib/audit';
import {sourceSignals,type SourceSignals} from '../lib/source-signals';
import {canonicalVerification} from '../lib/link-analysis';

export function SourceSignalReport({report,category,signals:provided}:{report?:Report;signals?:SourceSignals;category?:'AEO'|'GEO'}){
 const [answerLimit,setAnswerLimit]=useState(10),[entityLimit,setEntityLimit]=useState(20);
 const signals=provided||(report?sourceSignals(report):null),canonical=report?canonicalVerification(report):null;
 if(!signals)return <p>No stored source-signal analysis is available. Re-audit the page to capture these observations.</p>;
 return <section className="source-signal-report" aria-label="Observable page signals">
  <p>{signals.scope} These observations do not add checks or alter the score formula.</p>
  {category!=='GEO'&&<details className="panel detail-accordion"><summary><strong>Answer signals · {signals.answers.length} question candidates</strong></summary><div className="detail-accordion-content">
   {!signals.answers.length&&<p>No question candidates detected in the stored main content. This page may not need a question-and-answer format.</p>}
   {signals.answers.slice(0,answerLimit).map((q,i)=><article className="project-observation" key={q.selector+'-'+i}><h4>{q.question}</h4><p>{q.signal} · {q.format} · REVIEW · {q.confidence} detection confidence</p><p>Location: {q.section} · distance: {q.distance===null?'Not measured':`${q.distance} DOM source positions`}</p><blockquote>{q.answer||'No adjacent answer block detected.'}</blockquote><p>{q.completenessSignals.join(' · ')}. {q.claritySignals.join(' · ')}.</p><p>{q.supportingExplanation?'Additional adjacent explanation detected.':'No additional adjacent explanation detected.'}</p>{q.supportingLinks.length>0&&<ul>{q.supportingLinks.map(l=><li key={l.url}><a href={l.url} target="_blank" rel="noreferrer">{l.text||l.url}</a></li>)}</ul>}{q.attributionSignals.length>0&&<p>Page attribution: {q.attributionSignals.join(' · ')}</p>}<p><strong>Limitation:</strong> {q.limitation}</p><details><summary>Captured question and answer evidence</summary><p>{q.questionEvidence.text}</p>{q.questionEvidence.snippet&&<pre><code>{q.questionEvidence.snippet}</code></pre>}{q.evidence.map((e,j)=><div key={j}><p>{e.text}</p><pre><code>{e.snippet}</code></pre></div>)}</details></article>)}
   {signals.answers.length>answerLimit&&<button className="secondary" onClick={()=>setAnswerLimit(n=>n+10)}>Show 10 more question candidates</button>}
  </div></details>}
  {category!=='AEO'&&<><details className="panel detail-accordion"><summary><strong>Entity/context signals · {signals.entities.length} declarations and context cues</strong></summary><div className="detail-accordion-content"><p>Entity/context signal detected means source evidence was captured. Recognition by Google or AI systems is not measured.</p>{!signals.entities.length&&<p>No supported entity/context signals detected.</p>}{signals.entities.slice(0,entityLimit).map((e,i)=><article className="project-observation" key={i}><h4>{e.value}</h4><p>{e.type} · {e.source} · {e.confidence} detection confidence · OBSERVATION</p><p>{e.page} · {e.section}</p><p>{e.evidence.text}</p><p>{e.limitation}</p><details><summary>Source evidence</summary><pre><code>{e.evidence.snippet||e.evidence.text}</code></pre>{e.evidence.selector&&<p>Technical selector: <code>{e.evidence.selector}</code></p>}</details></article>)}{signals.entities.length>entityLimit&&<button className="secondary" onClick={()=>setEntityLimit(n=>n+20)}>Show 20 more entity/context signals</button>}</div></details>
   <details className="panel detail-accordion"><summary><strong>Freshness signals · {signals.freshness?.status||'Historical source unavailable'}</strong></summary><div className="detail-accordion-content"><p>{signals.freshness?.limitation||'This snapshot did not store complete freshness candidates. Re-audit to capture the current signal model.'}</p>{signals.freshness?.conflicts.map(c=><p key={c}>{c}</p>)}{signals.freshness?.signals.map((s,i)=><article className="project-observation" key={i}><h4>{s.type} · {s.date||'Invalid/uninterpreted date'}</h4><p>Source: {s.source} · declared: {s.raw||'Empty'}</p><p>{s.evidence.text||s.evidence.context}</p><details><summary>Captured date evidence</summary><pre><code>{s.evidence.snippet||s.raw}</code></pre></details></article>)}</div></details></>}
  {!category&&canonical&&<details className="panel detail-accordion"><summary><strong>Canonical target · {canonical.state}</strong></summary><div className="detail-accordion-content"><dl className="provenance-grid">{Object.entries({'Declared URL':canonical.declared||'Not declared','Resolved URL':canonical.resolved||'Not resolved','Syntax':canonical.syntax,'Relation':canonical.relation,'HTTP status':canonical.httpStatus??'Not verified','Final URL':canonical.finalURL||'Not verified','Final URL match':canonical.finalURLMatch===null?'Not verified':String(canonical.finalURLMatch)}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{canonical.redirectChain.map((h,i)=><p key={i}>HTTP {h.status}: {h.url} → {h.location}</p>)}{canonical.failure&&<p>{canonical.failure}</p>}<p>{canonical.limitation}</p></div></details>}
 </section>;
}
