export type Category = 'SEO'|'AEO'|'GEO';
export type Check={id:string;category:Category;name:string;status:'pass'|'review'|'fail'|'na';evidence:string;fix:string};
export type Report={label:string;mode:string;date:string;title:string;description:string;canonical:string;headings:{level:number;text:string}[];words:number;images:number;missingAlt:number;links:number;schemas:string[];checks:Check[];scores:Record<Category,number|null>;elapsed?:number;status?:number;keyword:string;notice:string};
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ');
const clean=(s:string)=>decode(s.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim());
function attrs(tag:string){const out:Record<string,string>={};for(const m of tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g))out[m[1].toLowerCase()]=decode(m[2]??m[3]??m[4]);return out;}
export function analyze(input:string,label:string,keyword='',mode='html'):Report{
 const html=mode!=='text';const source=input.replace(/<!--[\s\S]*?-->/g,'');const body=source.replace(/<(script|style|noscript)[\s\S]*?<\/\1\s*>/gi,'');
 const text=html?clean(body.replace(/<head[\s\S]*?<\/head>/gi,'')):input.trim();const words=text.split(/\s+/).filter(Boolean).length;
 const tags=(name:string)=>[...body.matchAll(new RegExp(`<${name}\\b[^>]*>`,'gi'))].map(m=>attrs(m[0]));
 const meta=(name:string)=>tags('meta').find(a=>a.name?.toLowerCase()===name||a.property?.toLowerCase()===name)?.content||'';
 const title=html?clean(source.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]||''):'';const description=meta('description');const canonical=tags('link').find(a=>a.rel?.toLowerCase().split(/\s+/).includes('canonical'))?.href||'';
 const headings=html?[...body.matchAll(/<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1\s*>/gi)].map(m=>({level:+m[1],text:clean(m[2])})):[];
 const imgs=tags('img');const missingAlt=imgs.filter(a=>!('alt'in a)).length;const links=tags('a').filter(a=>a.href);const schemas:string[]=[];let invalid=0;
 const walk=(v:unknown):void=>{if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object'){const o=v as Record<string,unknown>;if(o['@type'])schemas.push(...(Array.isArray(o['@type'])?o['@type']: [o['@type']]).map(String));if(o['@graph'])walk(o['@graph']);}};
 for(const m of source.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi)){if(attrs(m[1]).type?.toLowerCase()==='application/ld+json'){try{walk(JSON.parse(m[2]));}catch{invalid++;}}}
 const checks:Check[]=[];const add=(id:string,category:Category,name:string,status:Check['status'],evidence:string,fix:string)=>checks.push({id,category,name,status:html?status:(id.startsWith('content')?status:'na'),evidence:html||id.startsWith('content')?evidence:'Not measurable from plain text.',fix});
 add('title','SEO','Page title',title?'pass':'fail',title?`${title.length} characters · ${title}`:'No title element found.','Write a unique, descriptive title that matches the page.');
 add('description','SEO','Meta description',description?'pass':'review',description?`${description.length} characters · ${description}`:'No meta description found.','Add a useful page summary. Search engines may choose a different snippet.');
 add('h1','SEO','Main heading',headings.filter(h=>h.level===1).length===1?'pass':'review',`${headings.filter(h=>h.level===1).length} H1 headings detected.`,'Use a clear main heading; review multiple headings for a meaningful structure.');
 add('canonical','SEO','Canonical declaration',canonical?'pass':'review',canonical||'No canonical link declared.','Review duplicate URLs and declare the preferred URL where appropriate. Presence alone does not prove correctness.');
 const robots=meta('robots');add('index','SEO','Indexing directives',/\b(noindex|none)\b/i.test(robots)?'review':'pass',robots||'No restrictive robots meta detected. HTTP headers and actual index status are separate checks.','If this page should rank, remove unintended noindex directives. Keep intentional exclusions.');
 add('alt','SEO','Image alternatives',missingAlt?'review':'pass',`${missingAlt} of ${imgs.length} images lack an alt attribute.`,'Add descriptive alt text to informative images; use empty alt for decorative images.');
 add('lang','SEO','Document language',tags('html')[0]?.lang?'pass':'review',tags('html')[0]?.lang||'No language attribute detected.','Declare the content language on the html element.');
 add('viewport','SEO','Mobile viewport',meta('viewport')?'pass':'review',meta('viewport')||'No viewport meta found.','Use a responsive viewport and test the actual layout on mobile.');
 add('content-keyword','SEO','Target topic',!keyword?'na':text.toLowerCase().includes(keyword.toLowerCase())?'pass':'review',keyword?`Target phrase “${keyword}” ${text.toLowerCase().includes(keyword.toLowerCase())?'appears':'was not found'} in the extracted text.`:'Set an optional target phrase to check its presence.','Address the search intent naturally. Avoid keyword stuffing.');
 add('content-structure','AEO','Scannable structure',(html?headings.some(h=>h.level===2):/\n\s*\n/.test(text))?'pass':'review',html?`${headings.filter(h=>h.level===2).length} H2 headings detected.`:'Paragraph breaks checked.','Organize useful answers into clearly labeled sections. This is an editorial heuristic.');
 const questions=html?headings.filter(h=>/\?|^(how|what|why|when|where|who|can|does|is)\b/i.test(h.text)).length:(text.match(/\?/g)||[]).length;
 add('content-question','AEO','Explicit questions',questions?'pass':'review',`${questions} question signals detected.`,'When appropriate to the page, answer real audience questions directly. Questions are not required for every page.');
 const lists=/<(ul|ol|table)\b/i.test(body)||(!html&&/^\s*([-*]|\d+[.)])\s/m.test(text));add('content-list','AEO','Lists and comparisons',lists?'pass':'review',lists?'A list or table structure was detected.':'No list or table structure detected.','Use steps, lists or comparisons when they help the reader. Do not add them solely for a score.');
 add('schema','AEO','Structured data syntax',invalid?'fail':schemas.length?'pass':'review',invalid?`${invalid} JSON-LD blocks failed JSON parsing.`:schemas.length?`Types: ${[...new Set(schemas)].join(', ')}. Syntax only; eligibility not validated.`:'No JSON-LD types detected; Microdata/RDFa are not inspected.','Use applicable structured data that matches visible content. Validate with Google Rich Results Test.');
 add('content-attribution','GEO','Author or organization attribution',html?(/\b(author|publisher)\b/.test(source)||/\bby\s+[A-Z]/.test(text)?'pass':'review'):(/\b(author|written by|published by)\b/i.test(text)?'pass':'review'),'Attribution is detected using text and markup signals; inspect it manually.','Identify who created the content and provide relevant credentials.');
 const refs=html?links.filter(a=>/^https?:\/\//i.test(a.href)&&!a.href.startsWith(label.replace(/\/[^/]*$/,''))).length:(text.match(/https?:\/\/\S+/g)||[]).length;
 add('content-sources','GEO','Supporting sources',refs?'pass':'review',`${refs} possible source links detected; link destinations and factual claims are not verified.`,'Link relevant primary sources for claims that need evidence. Review source credibility.');
 add('content-date','GEO','Date context',/\b20\d{2}[-/]\d{1,2}|datetime\s*=|dateModified|datePublished/i.test(source)?'pass':'review','Publication or update date signals checked.','For time-sensitive material, show an accurate publication or update date.');
 const scores=Object.fromEntries((['SEO','AEO','GEO'] as Category[]).map(c=>{const eligible=checks.filter(x=>x.category===c&&x.status!=='na');return[c,eligible.length?Math.round(eligible.reduce((n,x)=>n+(x.status==='pass'?1:x.status==='review'?.5:0),0)/eligible.length*100):null];})) as Report['scores'];
 return{label,mode,date:new Date().toISOString(),title,description,canonical,headings,words,images:imgs.length,missingAlt,links:links.length,schemas:[...new Set(schemas)],checks,scores,keyword,notice:'Checklist scores are transparent heuristics, not ranking predictions or AI visibility measurements. URL audits inspect initial HTML only, without JavaScript rendering. No backlinks, search volume, Core Web Vitals, or actual index status are measured.'};
}
export const SAMPLE=`<!doctype html><html lang="en"><head><title>Workplace compliance training | Sample company</title><meta name="description" content="Practical compliance training for teams. Learn how to choose a course and make workplace policies easier to understand."><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="canonical" href="https://example.com/training"></head><body><h1>Workplace compliance training</h1><p>Help your team understand workplace policies through practical examples and clear learning paths.</p><h2>Why does compliance training matter?</h2><p>Training helps employees understand expectations and know where to ask for support. Start with the risks and responsibilities relevant to each role.</p><h2>Choose a course for your team</h2><ol><li>Identify learning goals.</li><li>Choose relevant scenarios.</li><li>Review feedback and update content.</li></ol><img src="team.webp"><a href="/courses">Explore courses</a></body></html>`;
