import type {Report} from './audit';
import {currentPageAttempts} from './website-findings';

export const CROSS_PAGE_VERSION='2.1';
export type CrossPageGroup={kind:'Duplicate title'|'Duplicate meta description'|'Duplicate H1'|'Similar content';value:string;urls:string[];similarity?:number;method:string;why:string;confidence:'observed'|'heuristic';evidence:string[];wordsCompared?:[number,number];sharedShingles?:number;projectId?:string|null;auditId?:string|null;pageIds?:Array<string|null>;finalUrls?:Array<string|null>;analysisVersion:string;measuredAt:string|null};
const normalize=(s:string)=>s.normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim();
const words=(s:string)=>normalize(s).split(/\s+/).filter(Boolean);
const shingles=(tokens:string[])=>{const result=new Set<string>();for(let i=0;i<=tokens.length-5;i++)result.add(tokens.slice(i,i+5).join(' '));return result;};
type Entry={url:string;id?:string;report:Report};
function trace(entries:Entry[]){return {projectId:entries[0]?.report.auditContext?.projectId??null,auditId:entries[0]?.report.auditContext?.auditId??null,pageIds:entries.map(e=>e.id||e.report.auditContext?.pageId||null),finalUrls:entries.map(e=>e.report.fetch?.finalURL||null),analysisVersion:CROSS_PAGE_VERSION,measuredAt:entries.map(e=>e.report.date).filter(Boolean).sort().at(-1)||null};}
/** Source snapshot relationships only. Never infer rankings, index status or intentional duplication. */
export function comparePages(pages:{url:string;id?:string;report:Report|null;status?:string;audited?:string}[]){
 const latest=currentPageAttempts(pages.map(p=>({...p,audited:p.audited??p.report?.date})));
 const entries:Entry[]=latest.filter(p=>p.report&&(!p.status||p.status==='completed')).map(p=>({url:p.url,id:p.id,report:p.report!})),groups:CrossPageGroup[]=[];
 for(const kind of ['Duplicate title','Duplicate meta description','Duplicate H1'] as const){const index=new Map<string,{value:string;pages:Entry[]}>();for(const p of entries){const values=kind==='Duplicate title'?[p.report.title]:kind==='Duplicate meta description'?[p.report.description]:p.report.headings.filter(h=>h.level===1).map(h=>h.text);for(const value of values){const key=normalize(value);if(!key)continue;const found=index.get(key)||{value,pages:[]};if(!found.pages.some(other=>other.url===p.url))found.pages.push(p);index.set(key,found);}}for(const matched of index.values())if(matched.pages.length>1)groups.push({kind,value:matched.value,urls:matched.pages.map(e=>e.url),method:'Exact normalized '+(kind==='Duplicate H1'?'content H1':'metadata')+' comparison',why:'The captured '+(kind==='Duplicate H1'?'main-content H1':'metadata value')+' matches after case and whitespace normalization.',confidence:'observed',evidence:[matched.value],...trace(matched.pages)});}
 // Reuse normalized main-content paragraph blocks. Repeated site-wide blocks are excluded only
 // when they occur on at least three pages and account for at least 30% of this snapshot.
 const blocks=entries.map(e=>{const paragraphs=e.report.pageDocument?.content?.paragraphs?.map(p=>p.text).filter(Boolean);return {entry:e,segments:paragraphs?.length?paragraphs:[e.report.contentText||'']};});
 const frequency=new Map<string,number>();for(const item of blocks){const unique=new Set(item.segments.map(normalize).filter(s=>words(s).length>=8));for(const segment of unique)frequency.set(segment,(frequency.get(segment)||0)+1);}
 const minRepeat=Math.max(3,Math.ceil(entries.length*.3));
 const candidates=blocks.map(({entry,segments})=>{const kept=segments.filter(s=>{const key=normalize(s);return words(key).length<8||(frequency.get(key)||0)<minRepeat;});const tokens=words(kept.join(' ')).slice(0,2000);return {entry,tokens,shingles:shingles(tokens)};}).filter(c=>c.tokens.length>=80&&c.shingles.size);
 const exact=new Map<string,number[]>();const signatures=candidates.map(c=>[...c.shingles].sort().join('\u0001'));
 signatures.forEach((signature,i)=>{const matches=exact.get(signature)||[];matches.push(i);exact.set(signature,matches);});
 for(const matches of exact.values())if(matches.length>1){const members=matches.map(i=>candidates[i]);groups.push({kind:'Similar content',value:'Main-content overlap to review',urls:members.map(m=>m.entry.url),similarity:100,method:'Identical retained five-word shingle sets after recurrent paragraph exclusion',why:'The retained initial-HTML main content has the same normalized five-word sequences across these pages. This is a review candidate, not a search-engine duplicate-content determination.',confidence:'heuristic',evidence:[...members[0].shingles].slice(0,3),wordsCompared:[members[0].tokens.length,members[1].tokens.length],sharedShingles:members[0].shingles.size,...trace(members.map(m=>m.entry))});}
 const posting=new Map<string,number[]>();const pairs=new Set<string>();
 for(let i=0;i<candidates.length;i++){for(const shingle of candidates[i].shingles){const previous=posting.get(shingle)||[];for(const j of previous)if(signatures[i]!==signatures[j])pairs.add(`${j}:${i}`);previous.push(i);posting.set(shingle,previous);}}
 for(const pair of pairs){const [i,j]=pair.split(':').map(Number),a=candidates[i],b=candidates[j];if(!a||!b)continue;let shared=0;const sample:string[]=[];for(const value of a.shingles)if(b.shingles.has(value)){shared++;if(sample.length<3)sample.push(value);}const score=shared/(a.shingles.size+b.shingles.size-shared);if(score<.85)continue;groups.push({kind:'Similar content',value:'Main-content overlap to review',urls:[a.entry.url,b.entry.url],similarity:Math.round(score*100),method:'Five-word shingle Jaccard similarity after recurrent main-content paragraph exclusion',why:'The retained initial-HTML main content shares a high proportion of five-word sequences. This is a review candidate, not a claim of duplicate content or search-engine treatment.',confidence:'heuristic',evidence:sample,wordsCompared:[a.tokens.length,b.tokens.length],sharedShingles:shared,...trace([a.entry,b.entry])});}
 return {groups,compared:entries.length,similarityCompared:candidates.length,method:'Exact normalized metadata/H1 matches; similarity uses candidate pairs from five-word shingles, Jaccard overlap ≥85%, at least 80 retained words, first 2,000 words per page. Repeated paragraph blocks on ≥3 and ≥30% of audited pages are removed. Short or template-dominated pages are not compared for similarity; legacy reports may lack paragraph structure. Scores are unchanged.',analysisVersion:CROSS_PAGE_VERSION,insufficientContent:entries.length-candidates.length,candidatePairs:pairs.size};
}
