import { publicURL, robotsAllowed } from './url-safety';
import { publicFetch, boundedText, robotPolicy } from './web-fetch';

export type PageType='Home'|'Page'|'Blog / Post'|'Newsletter'|'Article'|'Category'|'Product'|'Other';
export type DiscoveredPage={url:string;type:PageType;typeSource:'URL estimate'|'Sitemap estimate'|'Markup signal';lastmod:string|null;source:string};
export type Discovery={site:string;pages:DiscoveredPage[];messages:string[];sitemaps:string[];limited:boolean;excluded:number;limit:number};

const decode=(s:string)=>s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&#(x[0-9a-f]+|\d+);/gi,(_,v)=>{const n=v.toLowerCase().startsWith('x')?parseInt(v.slice(1),16):parseInt(v,10);return n>0&&n<=0x10ffff?String.fromCodePoint(n):'';}).trim();

export function classifyPage(url:string,source='',schemas:string[]=[]):{type:PageType;typeSource:DiscoveredPage['typeSource']}{const u=new URL(url);const path=u.pathname.toLowerCase();if(path==='/')return{type:'Home',typeSource:'URL estimate'};if(schemas.includes('BlogPosting'))return{type:'Blog / Post',typeSource:'Markup signal'};if(schemas.includes('NewsArticle')||schemas.includes('Article'))return{type:'Article',typeSource:'Markup signal'};if(schemas.includes('Product'))return{type:'Product',typeSource:'Markup signal'};if(/\/(newsletter|newsletters|bulletin)(\/|$)/.test(path))return{type:'Newsletter',typeSource:'URL estimate'};if(/\/(category|categories|tag|tags)(\/|$)/.test(path))return{type:'Category',typeSource:'URL estimate'};if(/\/(blog|blogs|post|posts)(\/|$)/.test(path))return{type:'Blog / Post',typeSource:'URL estimate'};if(/\/(article|articles|news)(\/|$)/.test(path))return{type:'Article',typeSource:'URL estimate'};if(/\/(product|products|shop)(\/|$)/.test(path))return{type:'Product',typeSource:'URL estimate'};if(/post[-_]?sitemap|blog[-_]?sitemap/i.test(source))return{type:'Blog / Post',typeSource:'Sitemap estimate'};if(/category[-_]?sitemap|tag[-_]?sitemap/i.test(source))return{type:'Category',typeSource:'Sitemap estimate'};return{type:'Page',typeSource:'URL estimate'};}

export function parseSitemap(xml:string){const index=/<(?:[\w-]+:)?sitemapindex\b/i.test(xml);const urlset=/<(?:[\w-]+:)?urlset\b/i.test(xml);if(!index&&!urlset)throw new Error('Not a sitemap urlset or sitemap index.');const tag=index?'sitemap':'url';const entries=[...xml.matchAll(new RegExp(`<(?:[\\w-]+:)?${tag}\\b[^>]*>([\\s\\S]*?)<\\/(?:[\\w-]+:)?${tag}\\s*>`,'gi'))].map(m=>({url:decode(m[1].match(/<(?:[\w-]+:)?loc\b[^>]*>([\s\S]*?)<\/(?:[\w-]+:)?loc\s*>/i)?.[1]||''),lastmod:decode(m[1].match(/<(?:[\w-]+:)?lastmod\b[^>]*>([\s\S]*?)<\/(?:[\w-]+:)?lastmod\s*>/i)?.[1]||'')||null})).filter(e=>e.url);return{index,entries};}

function pageURL(raw:string,root:URL){try{const u=publicURL(new URL(raw,root).href);u.hash='';if(u.origin!==root.origin||u.search||/\.(pdf|png|jpe?g|gif|webp|svg|zip|mp4|xml|gz|css|js|woff2?)$/i.test(u.pathname))return null;if(/^\/(wp-admin|wp-login|admin|login)(\/|$)/i.test(u.pathname))return null;return u;}catch{return null;}}
function addPage(result:Discovery,seen:Set<string>,root:URL,raw:string,source:string,typeSource?:DiscoveredPage['typeSource'],lastmod:string|null=null){if(result.pages.length>=result.limit){result.limited=true;return false;}const u=pageURL(raw,root);if(!u){result.excluded++;return false;}if(seen.has(u.href))return false;seen.add(u.href);const inferred=classifyPage(u.href,source);result.pages.push({url:u.href,type:inferred.type,typeSource:typeSource||inferred.typeSource,lastmod,source});return true;}

async function homepageLinks(root:URL,result:Discovery,seen:Set<string>,policy:string){try{if(!robotsAllowed(policy,'/'))return;const {r,u}=await publicFetch(root.href,5000);if(u.origin!==root.origin||!r.ok)return;const html=await boundedText(r,800000);const links=[...html.matchAll(/<a\b[^>]*\bhref\s*=\s*["']([^"']+)["'][^>]*>/gi)].map(m=>decode(m[1]));for(const href of links){if(result.pages.length>=result.limit)break;addPage(result,seen,root,href,'Homepage link fallback','Markup signal');}}catch(e){result.messages.push(`Homepage link fallback: ${e instanceof Error?e.message:'could not read the homepage'}`);}}

async function wordpressLinks(root:URL,result:Discovery,seen:Set<string>,policy:string){if(result.pages.length>=result.limit)return;for(const [endpoint,type] of [['/wp-json/wp/v2/pages?per_page=100&_fields=link','Page'],['/wp-json/wp/v2/posts?per_page=100&_fields=link','Blog / Post']] as const){try{if(!robotsAllowed(policy,endpoint))continue;const {r,u}=await publicFetch(new URL(endpoint,root).href,5000);if(u.origin!==root.origin||!r.ok){await r.body?.cancel();continue;}const payload=JSON.parse(await boundedText(r,500000)) as unknown;if(Array.isArray(payload))for(const item of payload){const link=typeof item==='object'&&item&&'link' in item?(item as {link?:unknown}).link:null;if(typeof link==='string')addPage(result,seen,root,link,'WordPress REST API',type==='Page'?'Markup signal':'Sitemap estimate');}}catch{/* optional integration */}}}

export async function discoverSite(site:string):Promise<Discovery>{const root=publicURL(site);root.pathname='/';root.search='';root.hash='';const result:Discovery={site:root.origin,pages:[{url:root.href,...classifyPage(root.href),lastmod:null,source:'Homepage'}],messages:[],sitemaps:[],limited:false,excluded:0,limit:1000};const seen=new Set([root.href]);let policy='';try{policy=await robotPolicy(root);}catch(e){result.messages.push(`robots.txt could not be read; discovery continued with public URLs only (${e instanceof Error?e.message:'request failed'}).`);}const queue=[...policy.matchAll(/^\s*sitemap:\s*(https?:\/\/\S+)/gim)].map(m=>m[1]);queue.push(new URL('/sitemap.xml',root).href,new URL('/sitemap_index.xml',root).href,new URL('/wp-sitemap.xml',root).href);const visited=new Set<string>();const deadline=Date.now()+25000;let found=0;while(queue.length&&visited.size<12&&Date.now()<deadline&&result.pages.length<result.limit){const batch:string[]=[];while(queue.length&&batch.length<3){const raw=queue.shift()!;try{const u=publicURL(raw);if(u.origin!==root.origin){result.excluded++;continue;}if(visited.has(u.href))continue;visited.add(u.href);if(!robotsAllowed(policy,u.pathname+u.search)){result.messages.push(`Sitemap blocked by robots.txt: ${u.href}`);continue;}batch.push(u.href);}catch{result.excluded++;}}const outcomes=await Promise.all(batch.map(async url=>{try{const {r,u}=await publicFetch(url,5000);if(u.origin!==root.origin){await r.body?.cancel();throw new Error('Cross-domain sitemap redirect was skipped.');}if(!r.ok){await r.body?.cancel();if(r.status===404)return null;throw new Error(`HTTP ${r.status}`);}return{url,data:parseSitemap(await boundedText(r,2000000))};}catch(e){result.messages.push(`${url}: ${e instanceof Error?e.message:'Could not read sitemap'}`);return null;}}));for(const outcome of outcomes){if(!outcome)continue;found++;result.sitemaps.push(outcome.url);if(outcome.data.index){queue.push(...outcome.data.entries.map(e=>e.url));continue;}for(const e of outcome.data.entries){if(result.pages.length>=result.limit){result.limited=true;break;}addPage(result,seen,root,e.url,outcome.url,undefined,e.lastmod&&Number.isFinite(Date.parse(e.lastmod))?e.lastmod:null);}}}if(queue.length||Date.now()>=deadline){result.limited=true;result.messages.push('Discovery stopped at the safety limit: 12 sitemap files, 1,000 pages, or 25 seconds. The displayed pages are a partial inventory.');}if(!found)result.messages.push('No readable sitemap found at robots.txt declarations or standard sitemap paths.');if(result.pages.length===1){await homepageLinks(root,result,seen,policy);await wordpressLinks(root,result,seen,policy);}if(result.pages.length===1)result.messages.push('Only the homepage was discoverable from public links. Add a sitemap or publish crawlable navigation links to include more pages.');return result;}
