import {PublicError,mutationOrigin,ERROR_STATES} from './app-errors';
import { database } from '../db';
import type { Discovery,DiscoveredPage } from './discovery';
import type { Report } from './audit';
import {ownedProject} from './projects';
export type Run={id:string;project?:string|null;site:string;created:string;started?:string|null;finished?:string|null;config?:Record<string,unknown>|null;status:string;inventory:Discovery;selected:DiscoveredPage[];keyword:string;completed?:number;failed?:number};
export type PageAudit={id:string;url:string;audited:string;type:string;typeSource:string;status:'completed'|'failed';error:string|null;fetch?:import('./web-fetch').FetchRecord|null;report:Report|null};
export function owner(request:Request){const user=request.headers.get('oai-authenticated-user-id');if(!user)throw new PublicError('Sign in to load or save audit history.',401,'SIGN_IN_REQUIRED');return user;}
export async function readJSON(request:Request){mutationOrigin(request);const reader=request.body?.getReader();if(!reader)throw new PublicError('Request body is required.');let size=0;const decoder=new TextDecoder();let raw='';while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>16000){await reader.cancel();throw new PublicError('Request is too large.');}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new PublicError('Request must contain a JSON object.');return parsed as Record<string,unknown>;}
export async function ownedRun(id:string,user:string,project?:string|null,permission:'read'|'edit'='read'):Promise<Run>{const row=await database().prepare('SELECT id,owner,project,site,created,started,finished,config,status,inventory,selected,keyword FROM audit_runs WHERE id=?').bind(id).first<Record<string,string>>();if(!row||(row.project||null)!==(project||null))throw new PublicError('Audit was not found or you do not have access.',404,'AUDIT_NOT_FOUND');if(row.project)await ownedProject(row.project,user,permission);else if(row.owner!==user)throw new PublicError('Audit was not found or you do not have access.',404,'AUDIT_NOT_FOUND');return{id:row.id,project:row.project,site:row.site,created:row.created,started:row.started,finished:row.finished,config:row.config?JSON.parse(row.config):null,status:row.status,inventory:JSON.parse(row.inventory),selected:JSON.parse(row.selected),keyword:row.keyword};}
export async function runPages(id:string):Promise<PageAudit[]>{const rows=await database().prepare('SELECT id,url,audited,type,type_source,status,error,fetch,report FROM page_audits WHERE run=? ORDER BY audited DESC').bind(id).all<Record<string,string|null>>();return(rows.results||[]).map(r=>({id:r.id!,url:r.url!,audited:r.audited!,type:r.type!,typeSource:r.type_source!,status:r.status as PageAudit['status'],error:r.error,fetch:r.fetch?JSON.parse(r.fetch):null,report:r.report?JSON.parse(r.report):null}));}
export function routeError(e:unknown){if(e instanceof PublicError)return Response.json({error:e.message,code:e.code},{status:e.status});if(e instanceof SyntaxError)return Response.json({error:'Request data is invalid.',code:'INVALID_JSON'},{status:400});console.error('SearchScope request failed',e);return Response.json({error:ERROR_STATES[500].description,code:'INTERNAL_ERROR'},{status:500});}
