import { database } from '../db';
import type { Discovery,DiscoveredPage } from './discovery';
import type { Report } from './audit';
import {ownedProject} from './projects';
export type Run={id:string;project?:string|null;site:string;created:string;started?:string|null;finished?:string|null;config?:Record<string,unknown>|null;status:string;inventory:Discovery;selected:DiscoveredPage[];keyword:string;completed?:number;failed?:number};
export type PageAudit={id:string;url:string;audited:string;type:string;typeSource:string;status:'completed'|'failed';error:string|null;fetch?:import('./web-fetch').FetchRecord|null;report:Report|null};
export function owner(request:Request){const user=request.headers.get('oai-authenticated-user-id');if(!user)throw new Error('Sign in to load or save audit history.');return user;}
export async function readJSON(request:Request){const reader=request.body?.getReader();if(!reader)throw new Error('Request body is required.');let size=0;const decoder=new TextDecoder();let raw='';while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>16000){await reader.cancel();throw new Error('Request is too large.');}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();return JSON.parse(raw) as Record<string,unknown>;}
export async function ownedRun(id:string,user:string,project?:string|null):Promise<Run>{const row=await database().prepare('SELECT id,project,site,created,started,finished,config,status,inventory,selected,keyword FROM audit_runs WHERE id=? AND owner=?').bind(id,user).first<Record<string,string>>();if(!row||(row.project||null)!==(project||null))throw new Error('Audit was not found or you do not have access.');if(row.project)await ownedProject(row.project,user);return{id:row.id,project:row.project,site:row.site,created:row.created,started:row.started,finished:row.finished,config:row.config?JSON.parse(row.config):null,status:row.status,inventory:JSON.parse(row.inventory),selected:JSON.parse(row.selected),keyword:row.keyword};}
export async function runPages(id:string):Promise<PageAudit[]>{const rows=await database().prepare('SELECT id,url,audited,type,type_source,status,error,fetch,report FROM page_audits WHERE run=? ORDER BY audited DESC').bind(id).all<Record<string,string|null>>();return(rows.results||[]).map(r=>({id:r.id!,url:r.url!,audited:r.audited!,type:r.type!,typeSource:r.type_source!,status:r.status as PageAudit['status'],error:r.error,fetch:r.fetch?JSON.parse(r.fetch):null,report:r.report?JSON.parse(r.report):null}));}
export function routeError(e:unknown){const message=e instanceof Error?e.message:'Request could not be completed.';const status=/Sign in/.test(message)?401:/not found or/.test(message)?404:/temporarily unavailable/.test(message)?503:400;return Response.json({error:message},{status});}
