import type {Report} from './audit';
import {publicFetch,robotPolicy,type RedirectHop} from './web-fetch';
import {publicURL,robotsAllowed} from './url-safety';
import {normalizeURL} from './url-normalization';
import {errorType} from './web-fetch';
export type LinkResult={url:string;internal:boolean;status:number|null;firstStatus?:number|null;state:'ok'|'broken'|'http-error'|'restricted'|'unverified'|'unchecked';finalURL:string|null;redirects:RedirectHop[];error:string|null;errorType?:string|null;checkedAt:string|null;method:string|null;sourcePage?:string;purpose?:'link'|'canonical'};
export type CanonicalResult={declared:string;url:string|null;relation:'self'|'other'|'missing'|'invalid';observation:LinkResult|null;note:string};
export async function checkLinks(report:Report,{maxLinks=20,budgetMs=15000,known=[]}:{maxLinks?:number;budgetMs?:number;known?:LinkResult[]}={}){
 const unique=new Map<string,boolean>();let canonical:string|null=null;try{if(report.canonical)canonical=normalizeURL(report.canonical,report.pageDocument?.baseURL||report.label);}catch{}if(canonical)unique.set(canonical,new URL(canonical).origin===new URL(report.label).origin);for(const link of report.linkInventory||[])if(link.url&&link.internal!==null&&link.type!=='fragment')unique.set(normalizeURL(link.url),link.internal);
 const deadline=Date.now()+budgetMs,policies=new Map<string,Promise<string>>();
 const beforeRequest=async(u:URL)=>{let policy=policies.get(u.origin);if(!policy){policy=robotPolicy(u);policies.set(u.origin,policy);}if(!robotsAllowed(await policy,u.pathname+u.search))throw Error('robots.txt disallows link verification.');};
 const results:LinkResult[]=[];
 for(const [url,internal] of [...unique].sort(([a,ai],[b,bi])=>a===canonical?-1:b===canonical?1:Number(bi)-Number(ai))){const result:LinkResult={url,internal,status:null,firstStatus:null,state:'unchecked',finalURL:null,redirects:[],error:null,checkedAt:null,method:null,sourcePage:report.label,purpose:url===canonical?'canonical':'link'};results.push(result);const cached=known.find(r=>r.url===url&&r.checkedAt&&Date.now()-Date.parse(r.checkedAt)<300000&&r.status!==null&&r.state!=='unchecked');if(cached){Object.assign(result,cached,{sourcePage:report.label,method:'cached (≤5 minutes)',purpose:result.purpose});continue;}if(results.length>maxLinks||Date.now()>=deadline){result.error='Per-page link verification budget reached.';result.errorType='budget';continue;}
  try{publicURL(url);result.method='HEAD';let fetched=await publicFetch(url,4000,{method:'HEAD',beforeRequest,deadline});if([405,501].includes(fetched.r.status)){await fetched.r.body?.cancel();result.method='GET';fetched=await publicFetch(url,4000,{beforeRequest,deadline});}result.status=fetched.r.status;result.firstStatus=fetched.redirects[0]?.status??fetched.r.status;result.finalURL=fetched.u.href;result.redirects=fetched.redirects;result.checkedAt=new Date().toISOString();result.state=[404,410].includes(result.status)?'broken':[401,403,429].includes(result.status)?'restricted':result.status>=400?'http-error':result.status>=200&&result.status<300?'ok':'unverified';await fetched.r.body?.cancel();
  }catch(e){result.state='unverified';result.error=e instanceof Error?e.message:'Link could not be verified.';result.errorType=errorType(e);result.finalURL=(e as {finalURL?:string}).finalURL||null;result.redirects=(e as {redirects?:RedirectHop[]})?.redirects||[];result.firstStatus=result.redirects[0]?.status??null;result.checkedAt=new Date().toISOString();}
 }return results;
}
export function canonicalObservation(report:Report):CanonicalResult{let url:string|null=null;try{if(report.canonical)url=normalizeURL(report.canonical,report.pageDocument?.baseURL||report.label);}catch{}return{declared:report.canonical,url,relation:!report.canonical?'missing':!url?'invalid':url===normalizeURL(report.label)?'self':'other',observation:url?report.linkResults?.find(r=>r.url===url)||null:null,note:'A canonical to another page can be intentional. HTTP observations do not establish which URL a search engine will select.'};}
