import type {Report} from './audit';
import {publicFetch,robotPolicy,type RedirectHop} from './web-fetch';
import {publicURL,robotsAllowed} from './url-safety';
import {normalizeURL} from './url-normalization';
import {errorType} from './web-fetch';
export type LinkResult={url:string;internal:boolean;status:number|null;firstStatus?:number|null;state:'ok'|'broken'|'http-error'|'restricted'|'unverified'|'unchecked';finalURL:string|null;redirects:RedirectHop[];error:string|null;errorType?:string|null;checkedAt:string|null;method:string|null;sourcePage?:string;purpose?:'link'|'canonical'};
export type CanonicalResult={declared:string;url:string|null;relation:'self'|'other'|'missing'|'invalid';observation:LinkResult|null;note:string};
export function linkVerification(result:LinkResult){
 const blocked=['robots','robots-blocked','restricted','excluded'].includes(result.errorType||'')||[401,403,429].includes(result.status??0);
 const state=blocked?'BLOCKED':result.errorType==='budget'?'BUDGET_EXHAUSTED':result.errorType==='timeout'?'TIMEOUT':result.status!==null?result.status>=500?'VERIFIED_5XX':result.status>=400?'VERIFIED_4XX':result.status>=300?'VERIFIED_3XX':result.status>=200?'VERIFIED_2XX':'NOT_VERIFIED':result.error&&result.state!=='unchecked'?'REQUEST_ERROR':'NOT_VERIFIED';
 // Product policy: only confirmed 404/410 are labelled broken. Other HTTP errors require review.
 return {state,redirectState:result.redirects.length?'REDIRECTED':null,classification:[404,410].includes(result.status??0)?'ISSUE':'OBSERVATION',broken:[404,410].includes(result.status??0),confidence:result.status!==null?'High':'Low',httpStatus:result.status,firstStatus:result.firstStatus??null,finalURL:result.finalURL,redirects:result.redirects,error:result.error,checkedAt:result.checkedAt,limitation:'HTTP outcomes describe this request only. Permission limits, timeout, budget exhaustion and request errors do not establish a broken destination.'};
}
export function canonicalVerification(report:Report){
 let url:string|null=null;let syntax:'VALID'|'INVALID_SYNTAX'|'TARGET_NOT_VERIFIED'=report.canonical.trim()?'INVALID_SYNTAX':'TARGET_NOT_VERIFIED';let relation:'same-origin'|'external'|'unknown'='unknown';
 try{if(report.canonical.trim()){const base=report.pageDocument?.baseURL||report.label,canResolve=/^https?:\/\//i.test(base)||/^https?:\/\//i.test(report.canonical);const u=new URL(report.canonical,/^https?:\/\//i.test(base)?base:'https://example.invalid/');if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Invalid syntax');syntax='VALID';if(canResolve){url=normalizeURL(u.href);try{relation=u.origin===new URL(report.label).origin?'same-origin':'external';}catch{relation='unknown';}}}}catch{/* Invalid syntax, or no observed URL base. */}
 const observation=url?report.linkResults?.find(r=>r.url===url)||null:null,verified=observation?linkVerification(observation):null;
 const state=!url?syntax==='INVALID_SYNTAX'?'INVALID_SYNTAX':'TARGET_NOT_VERIFIED':!verified?'TARGET_NOT_VERIFIED':verified.state==='BLOCKED'?'TARGET_BLOCKED':verified.state==='TIMEOUT'?'TARGET_TIMEOUT':verified.state==='BUDGET_EXHAUSTED'||verified.state==='NOT_VERIFIED'?'TARGET_NOT_VERIFIED':verified.state==='REQUEST_ERROR'?'TARGET_ERROR':observation?.status===404?'TARGET_404':observation?.status!==null&&(observation?.status??0)>=400?'TARGET_ERROR':observation?.redirects.length?'TARGET_REDIRECTED':observation?.status===200?'TARGET_200':'VALID';
 return {declared:report.canonical||null,resolved:url,syntax,state,relation,httpStatus:observation?.status??null,redirectChain:observation?.redirects||[],finalURL:observation?.finalURL??null,finalURLMatch:observation?.finalURL&&url?normalizeURL(observation.finalURL)===url:null,failure:observation?.error??null,budgetUnavailable:verified?.state==='BUDGET_EXHAUSTED',observation:verified,limitation:'An unresolved or unverified target is not broken. Bounded HTTP evidence cannot establish the canonical URL selected by search engines.'};
}
export async function checkLinks(report:Report,{maxLinks=20,budgetMs=15000,known=[]}:{maxLinks?:number;budgetMs?:number;known?:LinkResult[]}={}){
 maxLinks=Math.max(0,Math.min(20,Math.floor(maxLinks)));budgetMs=Math.max(0,Math.min(15000,budgetMs));
 const unique=new Map<string,boolean>();const canonical=canonicalVerification(report).resolved;if(canonical)unique.set(canonical,new URL(canonical).origin===new URL(report.label).origin);for(const link of report.linkInventory||[])if(link.url&&link.internal!==null&&link.type!=='fragment')unique.set(normalizeURL(link.url),link.internal);
 const deadline=Date.now()+budgetMs,policies=new Map<string,Promise<string>>();
 const beforeRequest=async(u:URL)=>{let policy=policies.get(u.origin);if(!policy){policy=robotPolicy(u,deadline);policies.set(u.origin,policy);}if(!robotsAllowed(await policy,u.pathname+u.search))throw Error('robots.txt disallows link verification.');};
 const results:LinkResult[]=[];
 for(const [url,internal] of [...unique].sort(([a,ai],[b,bi])=>a===canonical?-1:b===canonical?1:Number(bi)-Number(ai))){const result:LinkResult={url,internal,status:null,firstStatus:null,state:'unchecked',finalURL:null,redirects:[],error:null,checkedAt:null,method:null,sourcePage:report.label,purpose:url===canonical?'canonical':'link'};results.push(result);const cached=known.find(r=>r.url===url&&r.checkedAt&&Date.now()-Date.parse(r.checkedAt)<300000&&r.status!==null&&r.state!=='unchecked');if(cached){Object.assign(result,cached,{sourcePage:report.label,method:'cached (≤5 minutes)',purpose:result.purpose});continue;}if(results.length>maxLinks||Date.now()>=deadline){result.error='Per-page link verification budget reached.';result.errorType='budget';continue;}
  try{publicURL(url);result.method='HEAD';let fetched=await publicFetch(url,4000,{method:'HEAD',beforeRequest,deadline});if([405,501].includes(fetched.r.status)){await fetched.r.body?.cancel();result.method='GET';fetched=await publicFetch(url,4000,{beforeRequest,deadline});}result.status=fetched.r.status;result.firstStatus=fetched.redirects[0]?.status??fetched.r.status;result.finalURL=fetched.u.href;result.redirects=fetched.redirects;result.checkedAt=new Date().toISOString();result.state=[404,410].includes(result.status)?'broken':[401,403,429].includes(result.status)?'restricted':result.status>=400?'http-error':result.status>=200&&result.status<300?'ok':'unverified';await fetched.r.body?.cancel();
  }catch(e){result.state='unverified';result.error=e instanceof Error?e.message:'Link could not be verified.';result.errorType=errorType(e);result.finalURL=(e as {finalURL?:string}).finalURL||null;result.redirects=(e as {redirects?:RedirectHop[]})?.redirects||[];result.firstStatus=result.redirects[0]?.status??null;result.checkedAt=new Date().toISOString();}
 }return results;
}
export function canonicalObservation(report:Report):CanonicalResult{const target=canonicalVerification(report);let self=false;try{self=!!target.resolved&&target.resolved===normalizeURL(report.label);}catch{}return{declared:report.canonical,url:target.resolved,relation:!report.canonical?'missing':!target.resolved?'invalid':self?'self':'other',observation:target.resolved?report.linkResults?.find(r=>r.url===target.resolved)||null:null,note:target.limitation};}
