import {PublicError} from './app-errors';
import {snapshotStatements} from './audit-snapshot';
import {database} from '../db';
import {owner,ownedRun,readJSON,routeError,runPages} from './history';
import {classifyPage} from './discovery';
import {auditURL} from './audit-service';
import {auditDiff} from './audit-diff';
import {analyzePageIntelligence} from './content-intelligence';
import type {Report} from './audit';

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
 try{const {id}=await params;await ownedRun(id,owner(request),new URL(request.url).searchParams.get('project'));const query=new URL(request.url).searchParams;const db=database();const revision=query.get('revision');
  if(revision){const row=await db.prepare('SELECT id,url,audited,status,error,fetch,report FROM audit_revisions WHERE run=? AND id=?').bind(id,revision).first<Record<string,string|null>>();if(!row)throw new PublicError('Revision not found or unavailable.');return Response.json({revision:{...row,report:row.report?JSON.parse(row.report):null}});}
  const url=query.get('url');if(!url)throw new PublicError('Page URL is required.');const rows=await db.prepare('SELECT id,url,audited,status,error,scores,issues,changes FROM audit_revisions WHERE run=? AND url=? ORDER BY audited DESC,id DESC LIMIT 50').bind(id,url).all<Record<string,string|null>>();return Response.json({revisions:(rows.results||[]).map(r=>({...r,scores:r.scores?JSON.parse(r.scores):null,issues:r.issues?JSON.parse(r.issues):null,changes:r.changes?JSON.parse(r.changes):null}))});
 }catch(e){return routeError(e);}
}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){
 try{const {id}=await params;const user=owner(request);const run=await ownedRun(id,user,new URL(request.url).searchParams.get('project'),'edit');const {url,keyword=run.keyword}=await readJSON(request);if(typeof url!=='string'||typeof keyword!=='string'||keyword.length>200)throw new PublicError('Invalid page or target phrase.');const discovered=run.selected.find(p=>p.url===url);if(!discovered)throw new PublicError('This page is not in the selected audit inventory.');
  const db=database();if(run.status==='complete')await db.batch(snapshotStatements(id,'Legacy baseline captured before re-audit'));const previous=await db.prepare('SELECT id,audited,status,error,report FROM page_audits WHERE run=? AND url=?').bind(id,url).first<Record<string,string|null>>();const before:Report|null=previous?.report?JSON.parse(previous.report):null;
  let report:Report|null=null,error:string|null=null,fetchRecord:import('./web-fetch').FetchRecord|null=null;try{report=await auditURL(url,keyword,previous?[]:(await runPages(id)).flatMap(p=>p.report?.linkResults||[]));}catch(e){error=e instanceof Error?e.message:'Page could not be audited.';fetchRecord=(e as {fetch?:import('./web-fetch').FetchRecord}).fetch||null;}
  const category=report?classifyPage(url,discovered.source,report.schemas):{type:discovered.type,typeSource:discovered.typeSource};const pageId=crypto.randomUUID();if(report)report.auditContext={pageId,projectId:run.project||null,auditId:id,requestedURL:url,pageType:category.type,depth:discovered.depth??null,discoverySource:discovered.source,referringURL:discovered.referringURL??null};const page={id:pageId,url,audited:new Date().toISOString(),...category,status:report?'completed':'failed',error,fetch:report?.fetch||fetchRecord,report};
  const snapshot=(r:Report|null)=>r?JSON.stringify(r):null;const issues=(r:Report|null)=>r?JSON.stringify(r.checks.filter(c=>['error','warning','opportunity'].includes(c.severity)).map(c=>({id:c.id,name:c.name,severity:c.severity,affectedCount:c.affectedCount}))):null;
  const operations=[];
  if(previous)operations.push(db.prepare('INSERT OR IGNORE INTO audit_revisions (id,run,url,audited,status,error,scores,issues,changes,report) SELECT ?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM audit_revisions WHERE run=? AND url=?)').bind(`legacy:${id}:${previous.id}`,id,url,previous.audited,previous.status,previous.error,before?JSON.stringify(before.scores):null,issues(before),JSON.stringify({baseline:true,resolved:[],introduced:[],scoreChanges:null}),previous.report,id,url));
  operations.push(db.prepare('INSERT INTO audit_revisions (id,run,url,audited,status,error,fetch,scores,issues,changes,report) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(page.id,id,url,page.audited,page.status,error,page.fetch?JSON.stringify(page.fetch):null,report?JSON.stringify(report.scores):null,issues(report),JSON.stringify(auditDiff(before,report)),snapshot(report)));
  operations.push(db.prepare('INSERT INTO page_audits (id,run,url,audited,type,type_source,status,error,fetch,report) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(run,url) DO UPDATE SET id=excluded.id,audited=excluded.audited,type=excluded.type,type_source=excluded.type_source,status=excluded.status,error=excluded.error,fetch=excluded.fetch,report=excluded.report').bind(page.id,id,url,page.audited,page.type,page.typeSource,page.status,error,page.fetch?JSON.stringify(page.fetch):null,snapshot(report)));
  if(report&&run.project){const insight=analyzePageIntelligence(report,page.type);operations.push(db.prepare('INSERT INTO page_intelligence (revision,run,project,page,analyzed,analysis_version,crawl_version,extraction_version,recommendation_version,payload) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(page.id,id,run.project,page.id,page.audited,insight.analysisVersion,insight.crawlVersion,insight.extractionVersion,insight.recommendationVersion,JSON.stringify(insight)));}
  operations.push(db.prepare(`UPDATE audit_runs SET started=COALESCE(started,?),finished=CASE WHEN (SELECT COUNT(*) FROM page_audits WHERE run=?)>=json_array_length(selected) THEN ? ELSE NULL END,status=CASE WHEN (SELECT COUNT(*) FROM page_audits WHERE run=?)>=json_array_length(selected) THEN 'complete' WHEN status='paused' THEN 'paused' ELSE 'running' END WHERE id=?`).bind(page.audited,id,page.audited,id,id));
  await ownedRun(id,user,new URL(request.url).searchParams.get('project'),'edit');operations.push(...snapshotStatements(id));await db.batch(operations);return Response.json({page});
 }catch(e){return routeError(e);}
}
