export const APP_VERSION='1.1.0';
export const FEATURES=[
 {area:'Inputs',feature:'Public URL, pasted HTML and pasted text audits',since:'1.0.0',status:'Available',scope:'One page at a time; initial HTML only.'},
 {area:'SEO',feature:'Page title, description, H1, canonical, robots directives, image alt, language, viewport and target phrase',since:'1.0.0',status:'Available',scope:'Source markup checks. Does not establish actual index status.'},
 {area:'AEO',feature:'Sections, audience questions, lists/tables and JSON-LD syntax',since:'1.0.0',status:'Available',scope:'Editorial signals and JSON syntax; not an answer-engine visibility measurement.'},
 {area:'GEO',feature:'Attribution, possible supporting links and date signals',since:'1.0.0',status:'Available',scope:'Heuristics; author expertise, factual claims and source quality require manual review.'},
 {area:'Reports',feature:'Evidence, suggestions, category filters, finding search and metadata outline',since:'1.0.0',status:'Available',scope:'Session-only results; no server-side report history.'},
 {area:'Exports',feature:'CSV task list and complete JSON report',since:'1.0.0',status:'Available',scope:'Downloads generated in the browser.'},
 {area:'SEO',feature:'Duplicate titles/descriptions, canonical syntax/conflicts, empty/skipped headings, image sizing/source hints, link names/destinations, HTTPS and Open Graph metadata',since:'1.1.0',status:'Available',scope:'12 additional source checks. Link destinations and rendering are not tested.'},
 {area:'AEO',feature:'Readable initial-content check',since:'1.1.0',status:'Available',scope:'Detects empty extracted content; JavaScript rendering remains untested.'},
 {area:'Reports',feature:'Error/warning/opportunity totals, priority action plan, why it matters, fix steps, affected elements, examples, retest instructions and reference links',since:'1.1.0',status:'Available',scope:'Confirmed errors are separated from contextual warnings and editorial opportunities.'},
 {area:'Exports',feature:'Detailed CSV and downloadable Markdown audit report',since:'1.1.0',status:'Available',scope:'Includes severity, priority, impact, steps, affected elements and verification.'},
 {area:'Documentation',feature:'Versioned feature inventory and added/changed/removed development log',since:'1.1.0',status:'Available',scope:'Visible in the app, with downloadable development documentation.'},
 {area:'Data',feature:'Keyword volumes, ranking and backlink databases',since:'—',status:'Not implemented',scope:'Needs a licensed provider and an integration.'},
 {area:'Data',feature:'Search Console metrics and actual index coverage',since:'—',status:'Not implemented',scope:'Needs verified-site access and an integration.'},
 {area:'Performance',feature:'PageSpeed Insights, Lighthouse and Core Web Vitals',since:'—',status:'Not implemented',scope:'No performance score or field data is currently collected.'},
 {area:'Crawl',feature:'Site-wide crawling, broken-link validation and rendered-JavaScript audits',since:'—',status:'Not implemented',scope:'Current auditing is single-page initial-source inspection.'},
 {area:'AI visibility',feature:'Measured mentions, citations and competitor visibility in AI answers',since:'—',status:'Not implemented',scope:'Checklist scores do not measure these outcomes.'},
 {area:'Projects',feature:'Persistent audit history, scheduled audits and automatic site changes',since:'—',status:'Not implemented',scope:'Results are in the current browser session. No automatic website edits.'},
];
export const RELEASES=[
 {version:'1.1.0',date:'2026-10-01',title:'Detailed issue reports and development tracking',added:['13 additional source/content checks: duplicate titles and descriptions; canonical syntax and declaration conflicts; empty headings and heading-level skips; image dimension and source hints; unnamed and empty/JavaScript links; HTTPS URL; readable initial content; social preview metadata.','Separate error, warning, improvement opportunity and unavailable totals.','Fix-first list sorted by severity and priority.','Per-finding impact, numbered fix steps, affected-element examples, confidence, reference and verification instructions.','Detailed CSV columns and downloadable Markdown audit report.','Feature inventory, release history and downloadable development log.'],changed:['Finding labels explain contextual issues instead of presenting every finding as a generic Review.','Report overview defaults to findings needing attention; passed and unavailable checks remain accessible.','HTTP noindex findings update severity and priority consistently.','Supporting-link classification compares URL origins rather than string prefixes.','Sample includes intentional duplicate-title and JSON-LD syntax errors plus contextual warnings.','Checklist totals and scores now include additional applicable checks; scores from different versions should not be compared directly.'],removed:['Generic one-sentence-only recommendation display.','Combined “to review” summary that concealed the distinction between errors and opportunities.'],validation:'Audit-engine and API fixtures, export assertions, TypeScript checking and production build. Browser and WebMCP interaction tests are unavailable in this environment.',limits:'No site-wide crawl, JavaScript rendering, ranking/backlink/keyword datasets, Core Web Vitals or measured AI citations.'},
 {version:'1.0.0',date:'2026-10-01',title:'Initial audit workspace',added:['Public one-page URL audits with crawler checks, bounded fetching and public-DNS preflight.','Pasted HTML and text analysis.','16 baseline checks across SEO, AEO and GEO.','Evidence, basic suggestions, checklist scores, categories, filtering and metadata outline.','CSV and JSON exports; built-in sample.','Coverage and usage guides; optional browser WebMCP action when supported.'],changed:[],removed:[],validation:'Audit extraction and API fixtures, TypeScript checking and production build. Browser and WebMCP interaction tests were unavailable.',limits:'Single page, source only, session-only reports. No third-party search/performance/AI datasets.'},
];
export function developmentMarkdown(){return `# SearchScope — Development log and feature inventory\n\nCurrent release: ${APP_VERSION}\n\nThis document is versioned with the application. It records implemented scope and changes; future items below are not implemented features.\n\n## Feature inventory\n\n| Area | Feature | First release | Status | Scope |\n| --- | --- | --- | --- | --- |\n${FEATURES.map(f=>`| ${f.area} | ${f.feature} | ${f.since} | ${f.status} | ${f.scope} |`).join('\n')}\n\n${RELEASES.map(r=>`## ${r.version} — ${r.date} — ${r.title}\n\n${(['added','changed','removed'] as const).map(k=>`### ${k[0].toUpperCase()+k.slice(1)}\n\n${r[k].length?r[k].map(item=>'- '+item).join('\n'):'None.'}\n`).join('\n')}\n### Validation\n\n${r.validation}\n\n### Remaining limits\n\n${r.limits}\n`).join('\n')}\n## Report interpretation\n\nErrors are observed source problems such as missing titles, duplicate titles, conflicting/malformed canonicals or invalid JSON-LD. Warnings need contextual review; opportunities are optional editorial or presentation improvements. Passed means the specific source check passed, not that the site has no SEO problems. Unavailable checks were not measured. HTML extraction remains a lightweight source scan. Every applicable check is weighted equally (pass 1, review 0.5, fail 0); unavailable checks are excluded. SEO/AEO/GEO scores are checklist summaries, not rank or citation forecasts.\n`;}
