import { publicURL,robotsAllowed,verifyDNS } from './url-safety';
export type RedirectHop={url:string;status:number;location:string};
export type FetchRecord={requestedURL:string;finalURL:string|null;status:number|null;firstStatus:number|null;redirects:RedirectHop[];fetchedAt:string;elapsed:number;contentType:string|null;bytes:number|null;errorType:string|null;error:string|null};
export function errorType(error:unknown){const s=error instanceof Error?error.message:String(error);return /robots|permission/i.test(s)?'robots-blocked':/redirect loop/i.test(s)?'redirect-loop':/too many redirects/i.test(s)?'redirect-limit':/timeout|timed out|aborted/i.test(s)?'timeout':/budget/i.test(s)?'budget':/does not return HTML/i.test(s)?'non-html':/HTTP 404|HTTP 410/i.test(s)?'not-found':/HTTP 401|HTTP 403|HTTP 429/i.test(s)?'restricted':/HTTP/i.test(s)?'http-error':/DNS/i.test(s)?'dns':/private|unsafe|domain|origin/i.test(s)?'excluded':/exceeds/i.test(s)?'response-size':'network';}
export async function publicFetch(url:string,timeout=10000,options:{method?:'HEAD'|'GET';beforeRequest?:(url:URL)=>Promise<void>;deadline?:number}={}){
 let u=publicURL(url);const redirects:RedirectHop[]=[];const visited=new Set<string>();
 try{for(let i=0;i<=5;i++){
  if(visited.has(u.href))throw Object.assign(new Error('Redirect loop detected.'),{redirects});visited.add(u.href);
  if(options.deadline&&Date.now()>=options.deadline)throw Object.assign(new Error('Request budget exhausted.'),{redirects});
  await options.beforeRequest?.(u);await verifyDNS(u.hostname);
  const r=await fetch(u,{method:options.method||'GET',redirect:'manual',signal:AbortSignal.timeout(Math.max(1,Math.min(timeout,options.deadline?options.deadline-Date.now():timeout))),headers:{'User-Agent':'SearchScopeAudit/1.4','Accept':'text/html,application/xml,text/xml,application/json,text/plain,*/*;q=0.2'}});
  if([301,302,303,307,308].includes(r.status)){
   const location=r.headers.get('location');await r.body?.cancel();if(!location)throw Object.assign(new Error('Redirect has no destination.'),{redirects});
   redirects.push({url:u.href,status:r.status,location:new URL(location,u).href});if(i===5)throw Object.assign(new Error('Too many redirects.'),{redirects});try{u=publicURL(new URL(location,u).href);}catch(e){throw Object.assign(e instanceof Error?e:new Error('Unsafe redirect destination.'),{redirects});}continue;
  }return {r,u,redirects};
 }throw new Error('Too many redirects.');}catch(e){throw Object.assign(e instanceof Error?e:new Error('Request failed.'),{redirects,finalURL:u.href});}
}
export async function boundedText(r:Response,max=1000000){const reader=r.body?.getReader();if(!reader)return '';let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new Error(`Response exceeds the ${Math.round(max/1000000)} MB limit.`);}chunks.push(value);}const all=new Uint8Array(size);let offset=0;for(const c of chunks){all.set(c,offset);offset+=c.length;}if(all[0]===31&&all[1]===139){const stream=new Blob([all]).stream().pipeThrough(new DecompressionStream('gzip'));return boundedText(new Response(stream),max);}return new TextDecoder().decode(all);}
export async function robotPolicy(target:URL){const {r,u}=await publicFetch(new URL('/robots.txt',target).href,5000);if(u.origin!==target.origin)throw new Error('robots.txt redirects to another domain. Enter the final website URL.');if(r.ok)return await boundedText(r,100000);if(r.status===404||r.status===410)return '';await r.body?.cancel();throw new Error(`Crawler permission could not be verified (robots.txt HTTP ${r.status}).`);}
export async function auditHTML(url:string){
 const start=Date.now(),record:FetchRecord={requestedURL:url,finalURL:null,status:null,firstStatus:null,redirects:[],fetchedAt:new Date().toISOString(),elapsed:0,contentType:null,bytes:null,errorType:null,error:null};
 try{const target=publicURL(url),policy=await robotPolicy(target);if(!robotsAllowed(policy,target.pathname+target.search))throw Error('robots.txt disallows this page. Paste authorized HTML instead.');const {r,u,redirects}=await publicFetch(target.href,10000,{beforeRequest:async u=>{if(u.origin!==target.origin)throw Error('URL redirects to another domain. Enter the final URL to verify crawler permissions.');if(!robotsAllowed(policy,u.pathname+u.search))throw Error('robots.txt disallows a redirect destination.');}});record.finalURL=u.href;record.status=r.status;record.firstStatus=redirects[0]?.status??r.status;record.redirects=redirects;record.contentType=r.headers.get('content-type');if(!r.ok){await r.body?.cancel();throw Error(`Website returned HTTP ${r.status}.`);}if(!/text\/html|application\/xhtml/i.test(record.contentType||'')){await r.body?.cancel();throw Error('This URL does not return HTML.');}const html=await boundedText(r);record.bytes=new TextEncoder().encode(html).length;record.elapsed=Date.now()-start;return{html,url:u.href,status:r.status,elapsed:record.elapsed,header:r.headers.get('x-robots-tag'),fetch:record};
 }catch(e){const detail=e as {redirects?:RedirectHop[];finalURL?:string};record.redirects=detail.redirects||record.redirects;record.finalURL=detail.finalURL||record.finalURL;record.firstStatus=record.redirects[0]?.status??record.status;record.elapsed=Date.now()-start;record.error=e instanceof Error?e.message:'Request failed.';record.errorType=errorType(e);throw Object.assign(e instanceof Error?e:new Error(record.error),{fetch:record});}
}
