import { publicURL,robotsAllowed,verifyDNS } from './url-safety';
export type RedirectHop={url:string;status:number;location:string};
export async function publicFetch(url:string,timeout=10000,options:{method?:'HEAD'|'GET';beforeRequest?:(url:URL)=>Promise<void>;deadline?:number}={}){
 let u=publicURL(url);const redirects:RedirectHop[]=[];const visited=new Set<string>();
 for(let i=0;i<=5;i++){
  if(visited.has(u.href))throw Object.assign(new Error('Redirect loop detected.'),{redirects});visited.add(u.href);
  if(options.deadline&&Date.now()>=options.deadline)throw Object.assign(new Error('Request budget exhausted.'),{redirects});
  await options.beforeRequest?.(u);await verifyDNS(u.hostname);
  const r=await fetch(u,{method:options.method||'GET',redirect:'manual',signal:AbortSignal.timeout(Math.max(1,Math.min(timeout,options.deadline?options.deadline-Date.now():timeout))),headers:{'User-Agent':'SearchScopeAudit/1.4','Accept':'text/html,application/xml,text/xml,application/json,text/plain,*/*;q=0.2'}});
  if([301,302,303,307,308].includes(r.status)){
   const location=r.headers.get('location');await r.body?.cancel();if(!location)throw Object.assign(new Error('Redirect has no destination.'),{redirects});
   redirects.push({url:u.href,status:r.status,location:new URL(location,u).href});if(i===5)throw Object.assign(new Error('Too many redirects.'),{redirects});try{u=publicURL(new URL(location,u).href);}catch(e){throw Object.assign(e instanceof Error?e:new Error('Unsafe redirect destination.'),{redirects});}continue;
  }return {r,u,redirects};
 }throw new Error('Too many redirects.');
}
export async function boundedText(r:Response,max=1000000){const reader=r.body?.getReader();if(!reader)return '';let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new Error(`Response exceeds the ${Math.round(max/1000000)} MB limit.`);}chunks.push(value);}const all=new Uint8Array(size);let offset=0;for(const c of chunks){all.set(c,offset);offset+=c.length;}if(all[0]===31&&all[1]===139){const stream=new Blob([all]).stream().pipeThrough(new DecompressionStream('gzip'));return boundedText(new Response(stream),max);}return new TextDecoder().decode(all);}
export async function robotPolicy(target:URL){const {r,u}=await publicFetch(new URL('/robots.txt',target).href,5000);if(u.origin!==target.origin)throw new Error('robots.txt redirects to another domain. Enter the final website URL.');if(r.ok)return await boundedText(r,100000);if(r.status===404||r.status===410)return '';await r.body?.cancel();throw new Error(`Crawler permission could not be verified (robots.txt HTTP ${r.status}).`);}
export async function auditHTML(url:string){const start=Date.now();const target=publicURL(url);const policy=await robotPolicy(target);if(!robotsAllowed(policy,target.pathname+target.search))throw new Error('robots.txt disallows this page. Paste authorized HTML instead.');const {r,u}=await publicFetch(target.href,10000,{beforeRequest:async u=>{if(u.origin!==target.origin)throw Error('URL redirects to another domain. Enter the final URL to verify crawler permissions.');if(!robotsAllowed(policy,u.pathname+u.search))throw Error('robots.txt disallows a redirect destination.');}});if(u.origin!==target.origin){await r.body?.cancel();throw new Error('URL redirects to another domain. Enter the final URL to verify crawler permissions.');}if(!r.ok){await r.body?.cancel();throw new Error(`Website returned HTTP ${r.status}.`);}if(!/text\/html|application\/xhtml/i.test(r.headers.get('content-type')||'')){await r.body?.cancel();throw new Error('This URL does not return HTML.');}const header=r.headers.get('x-robots-tag');return{html:await boundedText(r),url:u.href,status:r.status,elapsed:Date.now()-start,header};}
