import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const dir=await fs.mkdtemp(path.join(process.cwd(),'.sites-runtime','foundation-'));
const originalFetch=globalThis.fetch;
try{
 const files=['dom-extraction','audit','page-metrics','finding-guides','web-fetch','url-safety','link-analysis','discovery','cross-page','audit-diff','history','page-audit-route','audit-service'];
 for(const name of files){const source=(await fs.readFile(`lib/${name}.ts`,'utf8')).replace(/(['"])(?:\.\/|\.\.\/)([\w-]+)\1/g,(_,q,n)=>`${q}./${n}.mjs${q}`);await fs.writeFile(path.join(dir,name+'.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
 await fs.writeFile(path.join(dir,'db.mjs'),'export const database=()=>globalThis.__testDB;');
 const {extractDocument}=await import(path.join(dir,'dom-extraction.mjs'));const {analyze}=await import(path.join(dir,'audit.mjs'));
 const fixture=`<!doctype html><html lang="en"><head><title>A &amp; B</title><meta name="description" content="A > B"><script type="application/ld+json">${JSON.stringify({'@type':'Article',padding:'x'.repeat(2500)})}</script></head><body><nav><h1>Menu</h1><a href="/nav">Navigation</a></nav><main id="main"><h1>Content</h1><section id="hero"><h3>Useful section</h3><p>Read &copy; content here</p><img src="/one.webp" title="a > b"><img src="/two.webp" alt="" width="10" height="10"><a href="/missing">Missing page</a><a href="/redirect">Redirect</a><a href="https://external.net/">External</a><a href="/restricted">Restricted</a><a href="/loop">Loop</a><div hidden><h2>Hidden</h2>Ignore this</div><div aria-hidden="true">Hidden by ARIA</div><div style="display:none">Hidden style</div><div class="cookie-banner">Cookies</div><aside><h2>Sidebar</h2></aside></section></main><footer><h2>Footer</h2></footer></body></html>`;
 const dom=extractDocument(fixture,'https://publicsite.com/');assert.equal(dom.headings.length,2);assert.match(dom.mainText,/Read © content/);assert.doesNotMatch(dom.mainText,/Menu|Hidden|Ignore this|Cookies|Sidebar|Footer/);assert.equal(dom.links.find(l=>l.attrs.href==='/nav').internal,true);assert.equal(dom.links.find(l=>l.attrs.href.startsWith('https://external')).internal,false);
 const report=analyze(fixture,'https://publicsite.com/','','url');assert.equal(report.title,'A & B');assert.equal(report.description,'A > B');assert.equal(report.checks.find(c=>c.id==='schema').status,'pass');assert.equal(report.checks.length,29);
 const alt=report.checks.find(c=>c.id==='alt');assert.equal(alt.evidenceItems.length,1);assert.equal(alt.evidenceItems[0].section,'hero');assert.match(alt.evidenceItems[0].selector,/main:nth-of-type\(1\).*img:nth-of-type\(1\)/);assert.match(alt.evidenceItems[0].snippet,/title="a > b"/);assert.equal(report.checks.find(c=>c.id==='image-dimensions').evidenceItems.length,1);assert.equal(report.checks.find(c=>c.id==='heading-order').evidenceItems.length,1);assert.equal(analyze('<main><p>No title</p></main>','HTML').checks.find(c=>c.id==='title').evidenceItems[0].kind,'absence');
 assert.match(extractDocument('<main><p>Unclosed <b>content','https://publicsite.com').mainText,/Unclosed content/);
 const resolve=(root,selector)=>{let current=root;for(const part of selector.split(' > ')){const m=part.match(/^(.+):nth-of-type\((\d+)\)$/);assert.ok(m);current=current.childNodes.filter(n=>n.tagName===m[1])[+m[2]-1];assert.ok(current);}return current;};
 const {parse}=await import('parse5');assert.equal(resolve(parse(fixture),alt.evidenceItems[0].selector).tagName,'img');
 const originalImages=analyze(Array.from({length:150},(_,i)=>`<img src="/${i}.webp">`).join(''),'HTML');assert.equal(originalImages.checks.find(c=>c.id==='alt').evidenceItems.length,150);
 let crawlRequests=[];
 globalThis.fetch=async(input,options={})=>{const u=new URL(String(input));if(u.hostname==='cloudflare-dns.com')return Response.json({Answer:u.searchParams.get('type')==='A'?[{type:1,data:'93.184.216.34'}]:[]});crawlRequests.push(u.href);if(u.pathname==='/robots.txt')return new Response('User-agent: *\nDisallow: /blocked');if(/sitemap/.test(u.pathname)||u.pathname.startsWith('/wp-json'))return new Response(null,{status:404});if(u.pathname==='/missing')return new Response(null,{status:404});if(u.pathname==='/redirect')return new Response(null,{status:301,headers:{location:'/final'}});if(u.pathname==='/loop')return new Response(null,{status:302,headers:{location:'/loop'}});if(u.pathname==='/restricted')return new Response(null,{status:403});if(u.pathname==='/')return new Response('<main><a href="/a">A</a><a href="/blocked">Blocked</a></main>',{headers:{'content-type':'text/html'}});if(u.pathname==='/a')return new Response('<main><a href="/b">B</a></main>',{headers:{'content-type':'text/html'}});return new Response('<main><h1>Good page</h1><p>Content.</p></main>',{headers:{'content-type':'text/html'}});};
 const {checkLinks}=await import(path.join(dir,'link-analysis.mjs'));const results=await checkLinks(report,{maxLinks:20});assert.equal(results.find(r=>r.url.endsWith('/missing')).state,'broken');assert.equal(results.find(r=>r.url.endsWith('/restricted')).state,'restricted');assert.equal(results.find(r=>r.url.endsWith('/redirect')).redirects.length,1);assert.equal(results.find(r=>r.url.endsWith('/loop')).state,'unverified');assert.equal(results.find(r=>r.url.endsWith('/loop')).redirects.length,1);assert.ok((await checkLinks(report,{maxLinks:1})).some(r=>r.state==='unchecked'));
 const {discoverSite}=await import(path.join(dir,'discovery.mjs'));crawlRequests=[];const discovered=await discoverSite('https://publicsite.com',{maxDepth:1,maxPages:10});assert.equal(discovered.pages.find(p=>p.url.endsWith('/a')).depth,1);assert.equal(discovered.pages.find(p=>p.url.endsWith('/a')).referringURL,'https://publicsite.com/');assert.ok(!discovered.pages.some(p=>p.url.endsWith('/b')));assert.ok(!crawlRequests.includes('https://publicsite.com/blocked'));
 const {comparePages}=await import(path.join(dir,'cross-page.mjs'));const large='meaningful '.repeat(100);const r1=analyze(`<title>Duplicate</title><meta name="description" content="Same"><main><h1>Same heading</h1><p>${large}</p></main>`,'https://publicsite.com/a');const r2=analyze(`<title>Duplicate</title><meta name="description" content="Same"><main><h1>Same heading</h1><p>${large}</p></main>`,'https://publicsite.com/b');const comparison=comparePages([{url:'a',report:r1},{url:'b',report:r2}]);assert.equal(comparison.groups.length,4);
 const {auditDiff}=await import(path.join(dir,'audit-diff.mjs'));assert.equal(auditDiff(null,r1).baseline,true);assert.equal(auditDiff({...r1,version:'older'},r2).scopeChanged,true);
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const file of (await fs.readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(await fs.readFile('drizzle/'+file,'utf8'));
 class Statement{constructor(query){this.query=query;}bind(...args){this.args=args;return this;}async first(){return sql.prepare(this.query).get(...this.args)||null;}async all(){return {results:sql.prepare(this.query).all(...this.args)};}}
 globalThis.__testDB={prepare:q=>new Statement(q),batch:async statements=>{sql.exec('BEGIN');try{const results=statements.map(s=>sql.prepare(s.query).run(...s.args));sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
 const run='test-run',url='https://publicsite.com/a';sql.prepare('INSERT INTO audit_runs (id,owner,site,created,status,inventory,selected,keyword) VALUES (?,?,?,?,?,?,?,?)').run(run,'owner','https://publicsite.com',new Date().toISOString(),'complete','{}',JSON.stringify([{url,type:'Page',typeSource:'URL estimate',source:'Sitemap'}]),'');sql.prepare('INSERT INTO page_audits (id,run,url,audited,type,type_source,status,report) VALUES (?,?,?,?,?,?,?,?)').run('legacy',run,url,'2026-01-01','Page','URL estimate','completed',JSON.stringify(r1));
 const route=await import(path.join(dir,'page-audit-route.mjs'));const params={params:Promise.resolve({id:run})};const req=()=>new Request('https://app.local/api/runs/'+run+'/page',{method:'POST',headers:{'oai-authenticated-user-id':'owner','Content-Type':'application/json'},body:JSON.stringify({url})});assert.equal((await route.POST(req(),params)).status,200);assert.equal(sql.prepare('SELECT COUNT(*) AS count FROM audit_revisions').get().count,2);assert.equal((await route.POST(req(),params)).status,200);assert.equal(sql.prepare('SELECT COUNT(*) AS count FROM audit_revisions').get().count,3);assert.equal(sql.prepare('SELECT COUNT(*) AS count FROM page_audits').get().count,1);
 const historyRequest=new Request('https://app.local/api/runs/'+run+'/page?url='+encodeURIComponent(url),{headers:{'oai-authenticated-user-id':'owner'}});const history=await route.GET(historyRequest,params);assert.equal(history.status,200);assert.equal((await history.json()).revisions.length,3);const unauthorized=await route.GET(new Request(historyRequest.url,{headers:{'oai-authenticated-user-id':'other'}}),params);assert.equal(unauthorized.status,404);
 assert.equal(sql.prepare("EXPLAIN QUERY PLAN SELECT * FROM audit_revisions WHERE run=? AND url=? ORDER BY audited DESC").all(run,url).some(r=>r.detail.includes('idx_audit_revisions_run_url_audited')),true);sql.close();
 console.log('PASS: DOM entities/malformed HTML/main-content exclusions, heading scope, valid CSS selectors, precise full evidence, JSON-LD, link response/redirect/restriction/budget states, crawl depth/robots, cross-page groups, migration preservation, atomic revision history and ownership isolation.');
}finally{globalThis.fetch=originalFetch;delete globalThis.__testDB;await fs.rm(dir,{recursive:true,force:true});}
