import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const dir=await fs.mkdtemp(path.join(process.cwd(),'.sites-runtime','projects-'));
const sources=['lib/app-errors.ts','lib/accounts.ts','lib/project-access.ts','app/api/account/route.ts','app/api/account/invitations/route.ts','app/api/projects/[id]/access/route.ts','lib/audit-snapshot.ts','lib/cross-page.ts','lib/content-intelligence.ts','lib/normalized-page.ts','lib/projects.ts','lib/history.ts','lib/url-normalization.ts','lib/discovery.ts','lib/dom-extraction.ts','lib/web-fetch.ts','lib/url-safety.ts','lib/audit-result.ts','lib/audit.ts','lib/finding-guides.ts','lib/page-metrics.ts','lib/audit-diff.ts','lib/project-analysis.ts','lib/website-scores.ts','lib/link-analysis.ts','lib/page-audit-route.ts','lib/audit-service.ts','lib/report-export.ts','app/api/projects/route.ts','app/api/projects/[id]/route.ts','app/api/runs/route.ts','app/api/runs/[id]/route.ts','app/api/projects/[id]/compare/route.ts','app/api/projects/[id]/intelligence/route.ts'];
const names=new Map(sources.map((s,i)=>[path.resolve(s),`module-${i}.mjs`]));const fetchOriginal=globalThis.fetch;
const sql=new DatabaseSync(':memory:');
try{
 for(const file of sources){const source=(await fs.readFile(file,'utf8')).replace(/(['"])(\.[^'"]+)\1/g,(m,q,p)=>{const target=path.resolve(path.dirname(file),p)+'.ts';return path.resolve(path.dirname(file),p)===path.resolve('db')?`${q}./db.mjs${q}`:names.has(target)?`${q}./${names.get(target)}${q}`:m;});await fs.writeFile(path.join(dir,names.get(path.resolve(file))),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
 await fs.writeFile(path.join(dir,'db.mjs'),'export const database=()=>globalThis.__projectDB;');
 const load=file=>import(path.join(dir,names.get(path.resolve(file))));
 sql.exec('PRAGMA foreign_keys=ON');const migrations=(await fs.readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort();sql.exec(await fs.readFile('drizzle/'+migrations[0],'utf8'));
 sql.prepare('INSERT INTO audit_runs (id,owner,site,created,status,inventory,selected,keyword) VALUES (?,?,?,?,?,?,?,?)').run('legacy','alice','https://publicsite.com','2026-01-01','complete','{}','[]','');
 for(const file of migrations.slice(1))sql.exec(await fs.readFile('drizzle/'+file,'utf8'));
 assert.equal(sql.prepare('SELECT site,project FROM audit_runs WHERE id=?').get('legacy').project,null);
 class Statement{constructor(query){this.query=query;this.args=[];}bind(...args){this.args=args;return this;}async first(){return sql.prepare(this.query).get(...this.args)||null;}async all(){return{results:sql.prepare(this.query).all(...this.args)};}async run(){return sql.prepare(this.query).run(...this.args);}}
 globalThis.__projectDB={prepare:q=>new Statement(q),batch:async statements=>{sql.exec('BEGIN');try{const r=statements.map(s=>sql.prepare(s.query).run(...s.args));sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
 const request=(url,user='alice',method='GET',body)=>new Request('https://app.local'+url,{method,headers:user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.com','Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});
 const context=id=>({params:Promise.resolve({id})});const projects=await load('app/api/projects/route.ts'),projectRoute=await load('app/api/projects/[id]/route.ts'),runs=await load('app/api/runs/route.ts'),runRoute=await load('app/api/runs/[id]/route.ts'),pageRoute=await load('lib/page-audit-route.ts');
 assert.equal((await projects.GET(request('/api/projects',null))).status,401);
 const create=await projects.POST(request('/api/projects','alice','POST',{name:'Primary',site:'HTTPS://PUBLICSITE.COM:443/path?utm_source=test',description:'Test',type:'website'}));assert.equal(create.status,201);const {project}=await create.json();assert.equal(project.site,'https://publicsite.com');
 assert.equal((await projects.POST(request('/api/projects','alice','POST',{name:'Duplicate',site:project.site}))).status,400);
 assert.equal((await projects.POST(request('/api/projects','alice','POST',{name:'Not supported',site:'https://secondsite.com',type:'video'}))).status,400);
 const second=(await(await projects.POST(request('/api/projects','alice','POST',{name:'Second',site:'https://secondsite.com'}))).json()).project;
 assert.equal((await projectRoute.GET(request('/api/projects/'+project.id,'bob'),context(project.id))).status,404);
 assert.equal((await projectRoute.PATCH(request('/api/projects/'+project.id,'alice','PATCH',{name:'Renamed'}),context(project.id))).status,200);
 const imported=await projects.POST(request('/api/projects','alice','POST',{action:'import-legacy'}));assert.equal((await imported.json()).imported,1);assert.equal(sql.prepare('SELECT project FROM audit_runs WHERE id=?').get('legacy').project,project.id);
 assert.equal((await(await projects.POST(request('/api/projects','alice','POST',{action:'import-legacy'}))).json()).imported,0);
 globalThis.fetch=async value=>{const u=new URL(String(value));if(u.hostname==='cloudflare-dns.com')return Response.json({Answer:u.searchParams.get('type')==='A'?[{type:1,data:'93.184.216.34'}]:[]});if(u.pathname==='/robots.txt')return new Response('User-agent: *\nAllow: /');if(/sitemap/.test(u.pathname)||u.pathname.startsWith('/wp-json'))return new Response(null,{status:404});return new Response('<main><h1>Main</h1><a href="/page?product=1&utm_source=track">Product</a></main>',{headers:{'content-type':'text/html'}});};
 const created=await runs.POST(request('/api/runs?project='+project.id,'alice','POST',{project:project.id,site:project.site,limit:10,maxDepth:1}));assert.equal(created.status,200);const first=(await created.json()).run;assert.equal(first.project,project.id);assert.equal(first.config.maxDepth,1);assert.ok(first.inventory.pages.some(p=>p.url.endsWith('/page?product=1')));assert.ok(first.inventory.pages.every(p=>p.normalizedURL&&p.discoveredAt));
 assert.equal((await runs.POST(request('/api/runs','alice','POST',{project:project.id,site:second.site,limit:10,maxDepth:0}))).status,400);
 assert.equal((await runRoute.GET(request('/api/runs/'+first.id+'?project='+second.id),context(first.id))).status,404);assert.equal((await runRoute.GET(request('/api/runs/'+first.id),context(first.id))).status,404);
 assert.equal((await pageRoute.GET(request('/api/runs/'+first.id+'/page?project='+second.id+'&url='+encodeURIComponent(first.selected[0].url)),context(first.id))).status,404);
 assert.equal((await runRoute.GET(request('/api/runs/'+first.id+'?project='+project.id,'bob'),context(first.id))).status,404);
 const scoped=await(await runs.GET(request('/api/runs?project='+second.id))).json();assert.equal(scoped.runs.length,0);
 assert.equal((await pageRoute.POST(request('/api/runs/'+first.id+'/page?project='+project.id,'alice','POST',{url:first.selected[0].url}),context(first.id))).status,200);
 assert.equal((await pageRoute.POST(request('/api/runs/'+first.id+'/page?project='+project.id,'alice','POST',{url:first.selected[0].url}),context(first.id))).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM audit_revisions WHERE run=?').get(first.id).n,2);
 assert.equal((await projectRoute.PATCH(request('/api/projects/'+project.id,'alice','PATCH',{site:'https://thirdsite.com'}),context(project.id))).status,400);
 const allProjects=await(await projects.GET(request('/api/projects'))).json();assert.ok(allProjects.projects.find(p=>p.id===project.id).latestScores.SEO!==null);
 assert.equal((await projectRoute.DELETE(request('/api/projects/'+project.id,'alice','DELETE'),context(project.id))).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM audit_runs WHERE project=?').get(project.id).n,2);
 assert.equal((await runs.POST(request('/api/runs','alice','POST',{project:project.id,site:project.site,limit:10,maxDepth:0}))).status,400);assert.equal((await projectRoute.PATCH(request('/api/projects/'+project.id,'alice','PATCH',{status:'active'}),context(project.id))).status,200);
 const {normalizeURL}=await load('lib/url-normalization.ts');assert.equal(normalizeURL('https://SITE.com:443/%7Ea?product=1&utm_source=x#part'),'https://site.com/~a?product=1');assert.notEqual(normalizeURL('https://site.com/a'),normalizeURL('https://site.com/a/'));assert.notEqual(normalizeURL('https://site.com/?q=1'),normalizeURL('https://site.com/?q=2'));
 const {analyze}=await load('lib/audit.ts'),{aggregateIssues,linkGraph,compareRuns}=await load('lib/project-analysis.ts');const bad=analyze('<nav><h1>Menu</h1></nav><main><h1>Content</h1><h3>Section</h3><img src="/asset.webp"><a href="/a">A</a></main>','https://publicsite.com/','','url'),good=analyze('<main><h1>Content</h1><h2>Section</h2><img src="/asset.webp" alt="Training image"><a href="/a">A</a></main>','https://publicsite.com/','','url');
 assert.equal(bad.pageDocument.headings.length,3);assert.equal(bad.headings.length,2);const evidence=bad.checks.find(c=>c.id==='alt').evidenceItems[0];assert.equal(evidence.pageURL,bad.label);assert.equal(evidence.attributes.src,'/asset.webp');assert.equal(evidence.classification,'content');
 const p={id:'page',url:bad.label,audited:'2026-01-01',type:'Home',typeSource:'URL estimate',status:'completed',error:null,report:bad};const grouping=aggregateIssues([p,{...p,url:'https://publicsite.com/a'}]);assert.equal(grouping.find(g=>g.id==='alt').pages.length,2);const graph=linkGraph({...first,inventory:{...first.inventory,pages:[{url:bad.label},{url:'https://publicsite.com/a'}]}},[p]);assert.equal(graph.pages[1].incoming.length,1);
 const diff=compareRuns({run:first,pages:[p]},{run:{...first,id:'next'},pages:[{...p,report:good}]});assert.ok(diff.resolved>0);const introduced=compareRuns({run:first,pages:[{...p,report:good}]},{run:{...first,id:'regressed'},pages:[p]});assert.ok(introduced.introduced>0);const failure=compareRuns({run:first,pages:[p]},{run:{...first,id:'failed'},pages:[{...p,status:'failed',report:null,error:'Timeout'}]});assert.equal(failure.resolved,0);assert.equal(failure.changes[0].scoreChanges,null);const changed=compareRuns({run:first,pages:[p]},{run:{...first,id:'changed'},pages:[{...p,report:{...good,keyword:'Different'}}]});assert.equal(changed.resolved,0);
 const comparisonRoute=await load('app/api/projects/[id]/compare/route.ts','app/api/projects/[id]/intelligence/route.ts');assert.equal((await comparisonRoute.GET(request(`/api/projects/${second.id}/compare?before=${first.id}&after=legacy`),context(second.id))).status,404);
 const {reportCSV,reportMarkdown}=await load('lib/report-export.ts');assert.match(reportCSV(bad),/DOM evidence/);assert.match(JSON.stringify(bad),/pageDocument/);assert.match(reportMarkdown(bad),/How to improve/);
 // Finish all pages, freeze exact revision references, then change the live page.
 for(const item of first.selected)assert.equal((await pageRoute.POST(request('/api/runs/'+first.id+'/page?project='+project.id,'alice','POST',{url:item.url}),context(first.id))).status,200);
 const snapshotURL='/api/runs/'+first.id+'?project='+project.id+'&snapshot=1';
 const frozen=await(await runRoute.GET(request(snapshotURL),context(first.id))).json();assert.equal(frozen.snapshot.immutable,true);assert.equal(frozen.pages.length,first.selected.length);
 const savedFrozen=JSON.stringify(frozen.pages);const network=globalThis.fetch;
 globalThis.fetch=async(value,options)=>new URL(String(value)).hostname==='publicsite.com'&&!String(value).includes('robots.txt')?new Response('<title>Changed after snapshot</title><main><h1>New content</h1><p>Changed.</p></main>',{headers:{'content-type':'text/html'}}):network(value,options);
 assert.equal((await pageRoute.POST(request('/api/runs/'+first.id+'/page?project='+project.id,'alice','POST',{url:first.selected[0].url}),context(first.id))).status,200);
 const again=await(await runRoute.GET(request(snapshotURL),context(first.id))).json();assert.equal(JSON.stringify(again.pages),savedFrozen);
 const latest=await(await runRoute.GET(request('/api/runs/'+first.id+'?project='+project.id),context(first.id))).json();assert.ok(latest.pages.some(p=>p.report.title==='Changed after snapshot'));
 assert.equal((await runRoute.GET(request('/api/runs/'+first.id+'?project='+second.id+'&snapshot=1'),context(first.id))).status,404);
 const {normalizedPage}=await load('lib/normalized-page.ts');const normalized=normalizedPage(latest.pages.find(p=>p.report.title==='Changed after snapshot').report);assert.equal(normalized.projectId,project.id);assert.ok(normalized.pageId);assert.ok(normalized.content.paragraphs.length);assert.equal(normalized.links.incoming,null);
 const intelligenceRoute=await load('app/api/projects/[id]/intelligence/route.ts');const insightURL='/api/projects/'+project.id+'/intelligence?run='+first.id;const result=await intelligenceRoute.GET(request(insightURL),context(project.id));assert.equal(result.status,200);const insight=await result.json();assert.ok(insight.coverage.analyzed>0);assert.equal(insight.pages[0].analysisVersion,'2.0.0');assert.equal(insight.pages[0].projectId,project.id);assert.ok(insight.pages[0].contentStrength.signals.length);assert.equal((await intelligenceRoute.GET(request(insightURL,'bob'),context(project.id))).status,404);assert.equal((await intelligenceRoute.GET(request('/api/projects/'+second.id+'/intelligence?run='+first.id),context(second.id))).status,404);

 // Account/membership/transfer regression uses the actual route handlers and SQLite transactions.
 const accountRoute=await load('app/api/account/route.ts'),accessRoute=await load('app/api/projects/[id]/access/route.ts'),invitationRoute=await load('app/api/account/invitations/route.ts');
 const access=(user,input)=>accessRoute.POST(request('/api/projects/'+project.id+'/access',user,'POST',input),context(project.id));
 const accept=(user,id,confirm='Renamed')=>invitationRoute.POST(request('/api/account/invitations',user,'POST',{id,confirm}));
 const invite=async(email,role='viewer',action='invite')=>{const r=await access('alice',{action,email,role,confirm:'Renamed'});assert.equal(r.status,200,await r.clone().text());return (await r.json()).invitation.id;};
 assert.equal((await accountRoute.GET(request('/api/account',null))).status,401);
 assert.equal((await accountRoute.GET(request('/api/account','alice'))).status,200);
 assert.equal((await accountRoute.PATCH(request('/api/account','alice','PATCH',{name:'Alice',company:'Example',timezone:'Asia/Kolkata',image:'javascript:alert(1)'}))).status,400);
 assert.equal((await accountRoute.PATCH(request('/api/account','alice','PATCH',{name:'Alice',company:'Example',timezone:'Asia/Kolkata'}))).status,200);
 assert.equal(sql.prepare('SELECT email FROM accounts WHERE id=?').get('alice').email,'alice@example.com');
 const viewInvite=await invite('bob@example.com');
 assert.equal((await accept('wrong',viewInvite)).status,404);assert.equal((await accept('bob',viewInvite,'wrong confirmation')).status,400);
 assert.equal((await accept('bob',viewInvite)).status,200);assert.equal((await intelligenceRoute.GET(request(insightURL,'bob'),context(project.id))).status,200);assert.equal((await accept('bob',viewInvite)).status,400);
 assert.equal((await runRoute.GET(request('/api/runs/'+first.id+'?project='+project.id,'bob'),context(first.id))).status,200);
 assert.equal((await runRoute.GET(request('/api/runs/'+first.id+'?project='+project.id+'&snapshot=1','bob'),context(first.id))).status,200);
 assert.equal((await pageRoute.POST(request('/api/runs/'+first.id+'/page?project='+project.id,'bob','POST',{url:first.selected[0].url}),context(first.id))).status,403);
 const op=insight.opportunities[0];assert.ok(op);assert.equal((await intelligenceRoute.PATCH(request('/api/projects/'+project.id+'/intelligence','bob','PATCH',{run:first.id,opportunity:op.id,status:'Resolved'}),context(project.id))).status,403);const updated=await intelligenceRoute.PATCH(request('/api/projects/'+project.id+'/intelligence','alice','PATCH',{run:first.id,opportunity:op.id,status:'In Progress'}),context(project.id));assert.equal(updated.status,200,await updated.clone().text());assert.equal((await(await intelligenceRoute.GET(request(insightURL),context(project.id))).json()).statuses[op.id],'In Progress');
 assert.equal((await runRoute.PATCH(request('/api/runs/'+first.id+'?project='+project.id,'bob','PATCH',{status:'paused'}),context(first.id))).status,403);
 assert.equal((await access('bob',{action:'invite',email:'other@example.com',role:'admin'})).status,403);
 const editorInvite=await invite('editor@example.com','editor');assert.equal((await accept('editor',editorInvite)).status,200);
 assert.equal((await runRoute.PATCH(request('/api/runs/'+first.id+'?project='+project.id,'editor','PATCH',{status:'paused'}),context(first.id))).status,200);
 assert.equal((await projectRoute.PATCH(request('/api/projects/'+project.id,'editor','PATCH',{name:'Unauthorized'}),context(project.id))).status,403);
 const adminInvite=await invite('admin@example.com','admin');assert.equal((await accept('admin',adminInvite)).status,200);
 assert.equal((await access('admin',{action:'invite',email:'escalation@example.com',role:'admin'})).status,403);
 assert.equal((await access('admin',{action:'transfer',email:'admin@example.com',confirm:'Renamed'})).status,403);
 assert.equal((await access('admin',{action:'role',user:'editor',role:'admin'})).status,403);
 const expired=await invite('expired@example.com');sql.prepare('UPDATE project_invites SET expires=? WHERE id=?').run('2000-01-01',expired);assert.equal((await accept('expired',expired)).status,400);
 const revoked=await invite('revoked@example.com');assert.equal((await access('alice',{action:'revoke',invitation:revoked})).status,200);assert.equal((await accept('revoked',revoked)).status,400);
 const transfer=await invite('bob@example.com','owner','transfer');assert.equal(sql.prepare('SELECT owner FROM projects WHERE id=?').get(project.id).owner,'alice');
 const pagesBefore=JSON.stringify(sql.prepare('SELECT * FROM page_audits WHERE run=? ORDER BY id').all(first.id));const revisionsBefore=JSON.stringify(sql.prepare('SELECT * FROM audit_revisions WHERE run=? ORDER BY id').all(first.id));const sealedBefore=JSON.stringify(sql.prepare('SELECT * FROM audit_snapshots WHERE run=?').get(first.id));
 const transferAccepted=await accept('bob',transfer);assert.equal(transferAccepted.status,200,await transferAccepted.clone().text());assert.equal((await transferAccepted.json()).project,project.id);
 assert.equal(sql.prepare('SELECT owner FROM projects WHERE id=?').get(project.id).owner,'bob');assert.equal(sql.prepare('SELECT role FROM project_members WHERE project=? AND user=?').get(project.id,'alice').role,'admin');
 assert.equal(JSON.stringify(sql.prepare('SELECT * FROM page_audits WHERE run=? ORDER BY id').all(first.id)),pagesBefore);assert.equal(JSON.stringify(sql.prepare('SELECT * FROM audit_revisions WHERE run=? ORDER BY id').all(first.id)),revisionsBefore);assert.equal(JSON.stringify(sql.prepare('SELECT * FROM audit_snapshots WHERE run=?').get(first.id)),sealedBefore);
 assert.equal((await accept('bob',transfer)).status,400);assert.equal((await access('alice',{action:'transfer',email:'next@example.com',confirm:'Renamed'})).status,403);
 assert.equal((await access('bob',{action:'remove',user:'alice'})).status,200);
 assert.equal((await runRoute.GET(request('/api/runs/'+first.id+'?project='+project.id,'alice'),context(first.id))).status,404);
 assert.equal((await runRoute.GET(request('/api/runs/'+first.id+'?project='+project.id,'bob'),context(first.id))).status,200);
 assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM project_events WHERE project=? AND action=?').get(project.id,'ownership_transferred').n,1);
 const badOrigin=request('/api/account','bob','PATCH',{name:'Bad'});badOrigin.headers.set('Origin','https://attacker.example');assert.equal((await accountRoute.PATCH(badOrigin)).status,403);
 const {routeError}=await load('lib/history.ts');const log=console.error;console.error=()=>{};const unexpected=routeError(Error('SQLITE_ERROR secret-internal-value'));console.error=log;assert.equal(unexpected.status,500);assert.doesNotMatch(await unexpected.text(),/SQLITE|secret-internal/);
 console.log('PASS: stable account identity/profile validation; owner/admin/editor/viewer permissions; cross-project and creator-after-removal denial; recipient confirmation; wrong recipient; expiry, revocation and replay rejection; ownership transfer preserves page/revision/snapshot bytes and records one event; CSRF origin denial and internal-error sanitization.');
 console.log('PASS: additive legacy migration; Website project CRUD/duplicates/archive/restore; normalized query URLs; project-bound run creation; missing, wrong-project and wrong-owner access rejection; run/revision retention; 29-check evidence; recurring groups; partial link graph; run comparisons/failure/scope safeguards; latest scores and exports.');
}finally{sql.close();globalThis.fetch=fetchOriginal;delete globalThis.__projectDB;await fs.rm(dir,{recursive:true,force:true});}
